excaliburjs/Excalibur

- src/engine/Actions/Action.ts
> [Fixes #409] clearActions checks if currentAction is present

- README.md
- src/engine/Actions/Action.ts
- src/engine/Actions/ActionContext.ts
- src/engine/Actor.ts
- src/engine/Animation.ts
- src/engine/Camera.ts
- src/engine/Collision/BoundingBox.ts
- src/engine/Engine.ts
- src/engine/Group.ts
- src/engine/Input/Gamepad.ts
- src/engine/Input/Input.ts
- src/engine/Input/Keyboard.ts
- src/engine/Input/Pointer.ts
- src/engine/Interfaces/ILoadable.ts
- src/engine/Label.ts
- src/engine/Loader.ts
- src/engine/Particles.ts
- src/engine/Promises.ts
- src/engine/Resource.ts
- src/engine/Scene.ts
- src/engine/Sprite.ts
- src/engine/SpriteSheet.ts
- src/engine/TileMap.ts
- src/engine/Trigger.ts
For issues #415 
- Added intros and examples to all major classes of the API
- Added some known issues and notes for gotchas
- Fixed up some spelling issues/grammar
- Added some new issues based on what I reviewed
These should be ready to merge once TypeDoc releases the next version, fixing a couple bugs and adding a new cross-linking caption feature. I will keep this open until then and keep polishing.
> Polish up edge documentation

- GruntFile.js
- sandbox/web/Excalibur.Sandbox.csproj
- sandbox/web/index.html
- src/engine/Actor.ts
- src/engine/Drawing/Polygon.ts
- src/engine/Scene.ts
- src/engine/Traits/OffscreenCulling.ts
- src/spec/ActorSpec.ts
Fixed a bug where actors with no sprites would never be culled
> Moved culling up level

- sandbox/web/Excalibur.Sandbox.csproj
- sandbox/web/index.html
- sandbox/web/tests/collision/index.html
- sandbox/web/tests/collision/index.js
- sandbox/web/tests/collision/index.ts
- src/engine/Collision/CollisionPair.ts
- src/spec/ActorSpec.ts
Please review my changes on this one, make sure it makes sense
> Fix actor collision

- src/engine/Actor.ts
> Set drawing error message

- GruntFile.js
- package.json
- src/spec/ActorSpec.ts
- src/spec/UIActorSpec.ts
> Fix #368 with tests

- src/engine/Actor.ts
- src/spec/ActorSpec.ts
> Fix #364 with test

- src/engine/TileMap.ts
Closes #293, offscreen culling was broken
> Fix #293 TileMap culling to use clientWidth and clientHeight

- src/engine/Loader.ts
Improve audio loader source error message
> Close #476 Improved audio error message

- src/spec/ActorSpec.ts
- src/spec/CameraSpec.ts
- src/spec/ClassSpec.ts
- src/spec/CollectionSpec.ts
- src/spec/CollisionGroupSpec.ts
- src/spec/CollisionSpec.ts
- src/spec/ColorSpec.ts
- src/spec/EventSpec.ts
- src/spec/GroupSpec.ts
- src/spec/LabelSpec.ts
- src/spec/LogSpec.ts
- src/spec/MathSpec.ts
- src/spec/Mocks.ts
- src/spec/SortedListSpec.ts
- src/spec/TimerSpec.ts
- src/spec/UIActorSpec.ts
> Mock engine

- src/engine/Actor.ts
See #467 for discussion please
> Potentially Closes #467

- .settings/settings.json
- GruntFile.js
- src/engine/Engine.ts
- src/engine/Util/Detector.ts
This is what it looks like if all the tests fail.
Let me know if we should update this
> Close #386, Critical Feature detection

- src/engine/Scene.ts
- src/engine/Util/Util.ts
- src/spec/ActorSpec.ts
- src/spec/Excalibur.Tests.csproj
- src/spec/SceneSpec.ts
> Prevent duplicates in scene

- sandbox/web/src/game.ts
- src/engine/Actor.ts
- src/engine/Particles.ts
- src/spec/ActorSpec.ts
> Actor.addChild() is now Actor.add()

- .vscode/settings.json
- .vscode/tasks.json
- package.json
- sandbox/web/Excalibur.js
- sandbox/web/tests/animation/animation.js
- sandbox/web/tests/input/gamepad.js
- sandbox/web/tests/input/gamepad.ts
- src/engine/Events.ts
- src/engine/Input/Gamepad.ts
- src/spec/GamepadSpec.ts
- src/spec/Mocks.ts
> Fix gamepad detection

- sandbox/web/src/game.ts
- src/engine/Actor.ts
- src/engine/Collision/CollisionPair.ts
- src/engine/Engine.ts
- src/engine/EventDispatcher.ts
- src/engine/Input/Gamepad.ts
- src/engine/Input/Keyboard.ts
- src/engine/Input/Pointer.ts
- src/engine/Particles.ts
- src/engine/Scene.ts
- src/engine/Traits/CollisionDetection.ts
- src/engine/Traits/OffscreenCulling.ts
- src/spec/CollisionGroupSpec.ts
- src/spec/EventSpec.ts
> Deprecate old methods

- package.json
- sandbox/web/Excalibur.js
- sandbox/web/tests/input/index.ts
- sandbox/web/tests/spritefont/spritefont.html
- sandbox/web/tests/spritefont/spritefont.js
- sandbox/web/tests/spritefont/spritefont.ts
- src/engine/Drawing/SpriteSheet.ts
- src/engine/Label.ts
- src/engine/PostProcessing/ColorBlindCorrector.ts
@jedeen @kamranayub Please review
> Fix spritefont textalign #484

- src/engine/Actor.ts
@jedeen @kamranayub Please review
> Fix #514 actors need to translate before scale

- src/engine/Engine.ts
- src/engine/PostProcessing/ColorBlindCorrector.ts
- src/engine/PostProcessing/IPostProcessor.ts
@jedeen @kamranayub Double check nothing offends you.
> Update post processor documentation

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Closes #560 
Proposed Changes:
- Update Contributing document
- Add Code of Conduct
> Update CONTRIBUTING.md and add Code of Conduct

- sandbox/web/src/game.js
- sandbox/web/src/game.ts
Closes #609
Proposed Changes:
- Fix old references to player acceleration (`ax`) to new (`acc.x`)
> [Closes #609] Fix updating player acceleration

- bower.json
- package.json
Associated issue #628 
- Update package.json with new version number
- Update bower.json with new version number
Note: we still need to update docs/source/conf.py and docs/source/index.rst after the 0.7.0 release is tagged.
> Update version number for 0.7.0 release

- docs/source/index.rst
- Fix links to API doc versions
> Fix links to API versions in doc index

- src/engine/Actor.ts
- change one of 'pointerdown' in Actor._checkForPointerOptIn to 'pointerup' since this is clearly a typo;
- also don't covert same string to lowercase 3-4 times in this method
> Fix converting same string to lower case 3-4 times

- src/engine/Loader.ts
- Move image creating to cached protected property
- Extract logo src, it's dimensions and background color to public properties for easier customizing
Actually I was looking into #481, when I noticed that logo gets loaded huge amount of times, so I went to investigate it and managed to slightly optimize Loader and made it bit more flexible.
> Optimize Loader#draw

- src/engine/Engine.ts
- src/engine/Resources/Sound.ts
- src/spec/SoundSpec.ts
Closes #697
- Fix `Promise.wrap` references
> [#697] Fix old Promise.wrap references

- src/spec/SoundSpec.ts
Closes #699
- Clear appenders before running sound specs
> [#699] Silence logger in Sound spec

- docs/source/index.rst
- docs/source/installation.rst
> Add Yeoman docs

- README.md
> Add shrinkwrap troubleshooting

- npm-shrinkwrap.json
- package.json
- src/engine/Drawing/Color.ts
- src/engine/Engine.ts
- src/engine/Input/Gamepad.ts
- src/engine/Util/DrawUtil.ts
Closes #715
- Update TSC to 2.0.10
- Update shrinkpacked deps
> [#715] Update to Typescript 2.0

- CHANGELOG.md
- src/engine/Loader.ts
- src/spec/EngineSpec.ts
- src/spec/ResourceSpec.ts
- src/spec/TestUtils.ts
- src/spec/UIActorSpec.ts
Closes #565 
- Fixed a bug where Excalibur would not load a game with an empty loader
- Added a test to confirm and fix
> [#565] Fix loader with no resource bug

- CHANGELOG.md
- Added `ex.Random` entry to CHANGELOG
> Update CHANGELOG with Random change

- CHANGELOG.md
- docs/source/installation.rst
- Add new repo excaliburjs/example-cordova
- Update Installation docs
- Update CHANGELOG
> Add Cordova example project

- CHANGELOG.md
- docs/source/installation.rst
- Add excaliburjs/example-xamarin
- Add excaliburjs/example-electron
- Add link to Xamarin repo
- Add link to Electron repo
> Add Xamarin & Electron docs

- LICENSE.md
- README.md
To help GH detect the repo license
- Update license text
> Update BSD license

- docs/source/index.rst
- package.json
Update excalibur version 0.9.0
> Update Excalibur version

- src/engine/Engine.ts
- Added missing type annotation
> Fix warning when --noImplicitAny is enabled by adding a missing type

- CHANGELOG.md
- src/engine/Util/Util.ts
Closes #763 
- Added Object.assign functionality where approriate
> Object.assign added to Util.ts extend function

- .github/CONTRIBUTING.md
- Add public API docs to contributing
> Add public API info to CONTRIBUTING

- deploy-docs.js
Related #777
- Trigger site build on tagged commit or master branch
> [#777] Trigger docs build on Git tag release

- docs/source/conf.py
- docs/source/index.rst
Related #777
- Dynamically fetch latest release at build time
> [#777] Use latest tag in docs TOC

- CHANGELOG.md
- docs/source/installation.rst
Closes https://github.com/excaliburjs/excaliburjs.github.io/issues/14
-Correct link to Browserify  example
> fix link toBrowserify example in docs

- src/engine/Engine.ts
Debug mode was using a deprecated method when drawing FPS to the screen
> Update deprecated fps method call

- version.js
- Fix PR builds on Travis that do not have access to secure env vars
> Support community PR builds

- CHANGELOG.md
- src/engine/Algebra.ts
- src/spec/AlgebraSpec.ts
Closes #517
- Added a static method `distance` to the Vector class
- Added a test spec in AlgebraSpec.ts to unit test this method
> [#517] Add static method Vector.distance

- CHANGELOG.md
- src/engine/Actor.ts
- src/engine/Util/Util.ts
- src/spec/UtilSpec.ts
Closes #812 
- changed Util.removItemToArray to Util.removeItemFromArray
- added tests for this method
- changed a call in Actor to removeItemToArray to call the correct new method
> [#812] Rename Util.removeItemToArray

- src/engine/Actor.ts
Closes #797
- Clone when setting Vector props on Actor
> [#797] Clone when setting Vector props

- src/engine/Collision/BoundingBox.ts
- src/spec/BoundingBoxSpec.ts
- src/spec/PerlinSpec.ts
Closes #795 
- Fix raycast bug
- Add test for raycast demonstrating bug
- Rewrite raycasts to be slightly more efficient by avoiding branching
- Add a new method to calculate time to impact in raycasts
> [#795] Fix bug in raycasting

- CHANGELOG.md
- sandbox/tests/input/pointer.html
- sandbox/tests/input/pointer.ts
- src/engine/Actor.ts
- src/engine/Docs/Pointers.md
- src/engine/Engine.ts
- src/engine/Events.ts
- src/engine/Input/Pointer.ts
Closes #808 
- Added event "wheel"
- Added sandbox pointer wheel test
- Added docs
> [#808] Add PointerWheel event support

- CHANGELOG.md
- src/engine/Debug.ts
- src/engine/Engine.ts
- update CHANGELOG.md
- fix documentation typos
> Update files for 0.11.0 release

- deploy-docs.js
> Fix deploy-docs.js syntax error

- README.md
- Clarify prereqs and make it easier to read
> Clarify dev requirements in README

- .travis.yml
- Fix CI build with specific SASS gem
> Install specific sass gem that is compat with Ruby 1.9.x

- docs/source/quickstart.rst
Related to #856 
Credit: @StepanVanzuriak  
- Fix when ball hits Y position
- Update JSFiddle to point to latest
> Fix quickstart sample

- docs/source/installation.rst
- Update references to Yeoman generator npm commands
> Update excalibur Yeoman reference

- sandbox/tests/collision/touching.ts
- sandbox/tests/group/group.ts
- src/engine/Actor.ts
- src/engine/Collision/CollisionContact.ts
- src/engine/Engine.ts
- src/engine/Promises.ts
- src/engine/Scene.ts
- src/engine/Traits/TileMapCollisionDetection.ts
- src/engine/Trigger.ts
- src/spec/ActionSpec.ts
- src/spec/ActorSpec.ts
- src/spec/CollisionSpec.ts
- remove methods that have been marked @obsolete for more than one
release
- label all remaining @obsolete methods with custom message that
indicates in what release they will be removed
- replace internal usage of @obsolete methods
> Clean up obsolete methods

- docs/source/installation.rst
- Update `yo` command references
> Update yo command

- docs/source/features.rst
- docs/source/installation.rst
- Updates some documentation references to features
- Remove references to bower
> Update docs, remove bower

- .travis.yml
- Publish dists on tagged builds
> Update dist condition

- src/engine/Collision/CollisionContact.ts
> Fix typo for _applyBoxImpulse

- src/spec/TimerSpec.ts
- Increase test coverage for Timers
- see also #305
> Add test for timer.getTimeRunning

- CHANGELOG.md
- src/engine/Timer.ts
- src/spec/TimerSpec.ts
Closes #885
- Implements timer pause/unpause
- Adds tests
> [#885] Add timer pause/unpause

- package.json
- Remove phantom.js because we've switched to Chrome headless
> Remove Phantom.js

- CHANGELOG.md
- src/engine/Scene.ts
> Replace obsolete Scene.children with Scene.actors

- src/engine/Camera.ts
- src/engine/Docs/Cameras.md
Closes #908
- Updates documentation to clarify current process
- Kill some dead code in `BaseCamera`
- Removes `setActorToFollow` method on `BaseCamera` that doesn't work when set and is confusing
> [#908] Fix BaseCamera documentation

- GruntFile.js
- package-lock.json
- package.json
- src/engine/Actions/Action.ts
- src/engine/Actor.ts
- src/engine/Camera.ts
- src/engine/Collision/Body.ts
- src/engine/Docs/Cameras.md
- src/engine/Drawing/SpriteSheet.ts
- src/engine/Engine.ts
- src/engine/Input/Gamepad.ts
- src/engine/Input/Keyboard.ts
- src/engine/Input/Pointer.ts
- src/engine/Interfaces/IAudioImplementation.ts
- src/engine/Label.ts
- src/engine/Loader.ts
- src/engine/Resources/Resource.ts
- src/engine/Resources/Sound.ts
- src/engine/Scene.ts
- src/engine/TileMap.ts
- src/engine/Trigger.ts
- src/spec/KeyInputSpec.ts
- src/spec/SoundSpec.ts
Closes #794 
- Update to TSC 2.6
- Update TypeDoc to 0.9.0 (TSC 2.4)
- Fix compilation errors
- Fix TypeDoc errors
> Update TS 2.6 and TypeDoc 0.9.0

- karma.conf.js
> [bugfix] Fix ci

- src/engine/Docs/Physics.md
- src/engine/Physics.ts
Closes #937
- Update Physics sample in docs
- Update global acceleration docs
- Update collision type information
> [#937] Update docs to clarify rigid body physics operation

- README.md
> [chore] Add code coverage, rearrange badges

- sandbox/src/game.ts
- sandbox/tests/camera/lerp.ts
- sandbox/tests/rotation/rotation.ts
- sandbox/tests/scale/scale.ts
- sandbox/tests/scene/display-mode-position.ts
- src/engine/Input/Pointer.ts
- Remove core engine usage of deprecated properties
- Remove sandbox tests
> [chore] Remove deprecated pointer event access from samples and tests

- docs/source/installation.rst
- Provide more context around installation for developers who may not be as familiar with the ecosystem. I'd like to expand this to dedicated installation tutorials eventually.
> [chore] [docs] More context for installation

- docs/source/installation.rst
> [chore] [docs] Fix code blocks

- docs/source/quickstart.rst
getDrawWidth() and getDrawHeight() are replaced by the getters drawWidth and
drawHeight since 0.14.0
> [docs] Use drawWidth and drawHeight in Getting Started

- package-lock.json
> [chore] Fix package lock

- CHANGELOG.md
- src/engine/TileMap.ts
Add missing variable assignments to constructor
> [bugfix] Fix missing variable assignments in TileMapImpl

- deploy-docs.js
- package-lock.json
- package.json
- version.js
Related #777 
- Add 0.0.0 local version (addresses local npm linking issues)
- Use nearest Git tag for local version (clearer indication of what you're based off of)
- Simplify npm scripts
> Add better local version handling

- package-lock.json
- src/spec/CollisionSpec.ts
Closes #799
After some investigation, it  was determined that #799 has been fixed as a result of other changes in physics/collision refactoring, this just adds tests to verify the fix.
> [#799] Verify Actors killed on collision

- CHANGELOG.md
- sandbox/tests/tilemap/tilemap.ts
- src/engine/Camera.ts
- src/engine/Util/EasingFunctions.ts
- src/spec/CameraSpec.ts
- src/spec/EasingFunctionSpec.ts
Closes #944
- Correct move logic to only resolve the move after 100% complete
- Added tests
> [#944] Fix camera move chaining

- .vscode/extensions.json
> [#907] Add VSCode extension recommendations

- .github/CONTRIBUTING.md
Clarifying the process around volunteering and working on issues
> [chore] Update CONTRIBUTING.md

- CHANGELOG.md
- src/engine/Math/Random.ts
- src/spec/RandomSpec.ts
Closes #984 
- Add tests for `Random._pickSetWithDuplicates()`;
> [#977] Fix pick set with duplicates. Tests added.

- CHANGELOG.md
- src/engine/Scene.ts
- src/spec/SceneSpec.ts
Closes #982 
- added isCurrentScene() to scene objects
..* This is property is updated on activate(), deactivate() which is managed by engine.gotoScene.
Have not created/run unit tests.  This is forthcoming.
> [#982] Implement isCurrentScene convenience method

- src/engine/tsconfig.json
> [chore] Remove tsconfig rootDir param

- package.json
- Change version back to 0.0.1 for possible npm compatibility to get public site build working again
Just a shot in the dark in case the `0.0.0` is throwing the current site build error related to versions. We used to not have the version present.
> Change version to 0.0.1 for older npms?

- docs/source/quickstart.rst
Update getting started documentation
> [chore] Update getting started

- CHANGELOG.md
- sandbox/index.html
- sandbox/tests/sprite/sprite.html
- sandbox/tests/sprite/sprite.ts
- src/engine/Drawing/Sprite.ts
- src/spec/SpriteSpec.ts
Closes #980
- Ensure sprite context has width and height
> [#980] Firefox image regression

- CHANGELOG.md
- sandbox/index.html
- sandbox/tests/collisionvelocity/vel.html
- sandbox/tests/collisionvelocity/vel.ts
- src/engine/Collision/CollisionContact.ts
- src/spec/CollisionSpec.ts
Closes #986 
- Adjust how box collison handles velocity resolution
- Add visual test with original repro
> [#986] Fix box collision velocity resolution

- src/engine/Docs/Triggers.md
> [docs] Update the trigger documentation example

- src/engine/Actor.ts
> [chore] Fix typo

- README.md
- Add docs contributing info to README
> [chore] Add docs contribution info to README

- .gitignore
- CHANGELOG.md
- GruntFile.js
Closes #1057
- Add missing files into dist Loader.css/Loader.logo.png
> [#1057] Add missing files into dist for Loader

- karma.conf.js
- package-lock.json
- package.json
Fixes a regression caused by Chrome 71 where image based tests would fail
> [bugfix] Switch to puppeteer for Chrome 71

- CHANGELOG.md
- src/engine/Camera.ts
- src/engine/Docs/Cameras.md
- src/engine/Docs/Index.md
- src/engine/Docs/Scenes.md
- src/engine/Events.ts
- src/engine/Scene.ts
- src/engine/Util/Decorators.ts
- src/spec/CameraSpec.ts
- src/spec/DecoratorSpec.ts
Closes #1087 
- Change BaseCamera to Camera
- Update `@obsolete` to work on classes
> [#1087] Change BaseCamera to Camera

- CHANGELOG.md
- package-lock.json
- src/engine/Engine.ts
- src/spec/EngineSpec.ts
- src/spec/util/TestUtils.ts
Closes #1096
- Added `enableCanvasTransparency` property that will can enable/disable canvas transparency
- Updated default Engine options.
> [#1096] Add flag to IEngineOptions to set canvas transparency

- src/spec/EventSpec.ts
Closes #1107 
- wrote new test in EventSpec.ts asserting that event handlers are called in the order subscribed
> [#1107] Test event handler execution order

- .github/PULL_REQUEST_TEMPLATE.md
- STYLEGUIDE.md
> [#1102] Add new style guide

- sandbox/src/game.ts
- src/engine/Actions/Action.ts
- src/engine/Actor.ts
- src/engine/Collision/DynamicTreeCollisionBroadphase.ts
- src/engine/Drawing/SpriteSheet.ts
- src/spec/ActionSpec.ts
- src/spec/EventSpec.ts
- src/spec/LogSpec.ts
- src/spec/PromiseSpec.ts
> [#1105] Remove extraneous todos

- CHANGELOG.md
- package-lock.json
- package.json
- src/engine/Interfaces/IAudioImplementation.ts
- src/engine/Label.ts
- src/engine/Resources/Gif.ts
- src/engine/Util/WebAudio.ts
- src/engine/globals.d.ts
Closes #1052
Additional PRs pending for
- Upgrade to TypeScript 3.3.3
- Upgrade TypeDoc to latest 3.x support
- Fix broken TypeDoc references
- Patch lib.d.ts with new globals.d.ts
> [#1052] Upgrade Excalibur to TypeScript 3.x

- .vscode/extensions.json
- README.md
Closes #1111 
- updates the recommended extensions file and README to reference the more recent version of the TSLint extension.
> [#1111] Update TSLint extension references

- src/spec/EngineSpec.ts
Clean's up a test boot message from the test result log
> [chore] Suppress Engine test boot message

- src/engine/Docs/Cameras.md
- src/engine/Docs/TileMaps.md
- src/engine/Interfaces/Drawable.ts
> [chore] Clean-up missed interfaces

- src/engine/Resources/Gif.ts
- Remove `ex.` references in `Gif` module
> [chore] Remove ex references

- src/engine/Docs/Physics.md
> [docs] Add Collision Type matrix

- .github/CONTRIBUTING.md
- clarify the language around issue labels
- additional cleanup
> Clarify issue tags and language

- src/engine/Docs/Engine.md
- src/engine/Docs/Index.md
- src/engine/Docs/Pointers.md
- src/engine/Docs/PostProcessors.md
- src/engine/Engine.ts
- Update JSDoc to fix broken references
> [docs] Fix broken docs references

- src/engine/Actor.ts
- src/engine/Input/Pointer.ts
- src/engine/Util/Util.ts
- src/spec/PointerInputSpec.ts
Closes #1127 & Closes #1126 
- Move pointer types to `Pointer.ts` from `Actor.ts`
- Refactor to string enums
> [#1126] [#1127] Refactor pointers

- CHANGELOG.md
- src/engine/Actions/Action.ts
- src/engine/Actions/ActionContext.ts
- src/spec/ActionSpec.ts
- src/spec/ActorSpec.ts
Closes #1146
- Update moveBy, rotateBy, and scaleBy actions to work relative to position
> [#1146] Update moveBy, rotateBy, and scaleBy actions to work relative to position

- src/engine/Docs/Textures.md
I believe on `latest` this Loader call wants an array.
Closes #
- change 1
- change 2
> [docs] Fix Loader call example in Texture documentation

- src/engine/Docs/SpriteSheets.md
Swaps all var to const.
Updates `Loader` usage to pass an array instead of a single Resource.
Closes #
- change 1
- change 2
> [docs] ES6 updates to SpriteSheets.md

- README.md
Bower is no longer used. 😬 
- chore(README): Remove bower badge
- chore(README): Remove RTD badge
> [chore] README: Remove bower

- CHANGELOG.md
- src/engine/Actor.ts
- src/spec/ActorSpec.ts
Closes #875
- Set visible to false if opacity is 0 during update
> [#875] If the opacity of an Actor's drawing/color is 0, don't draw the actor

- src/spec/ActorSpec.ts
Linting error only appearing on windows
> [bugfix] Windows lint error

- CHANGELOG.md
- src/engine/Camera.ts
- src/spec/CameraSpec.ts
Closes #1299
- Update to 1 source of truth on position
- Add test
> [#1299] Fix non-vector backed camera position

- src/engine/Actor.ts
- drafted ex.Actor.draggable utility getter/setter
> [#1092] Add draggable getter/setter

- CHANGELOG.md
- src/engine/Algebra.ts
- src/spec/AlgebraSpec.ts
Closes #1340
- Add the `ex.vec(x: number, y: number): Vector` function
> #1340 Implement the vec() shorthand

- package-lock.json
- package.json
- src/engine/Drawing/Animation.ts
Closes #1101
- Update typescript to 3.7.4
> [#1101] Upgrade to TypeScript 3.7.4 :tada:

- package-lock.json
> [chore] Update npm audit

- src/stories/Actions.stories.ts
- Add move stories
- Add rotate stories
- Add scale stories
- Add ease stories
I don't use `repeatForever` on some stories due to https://github.com/excaliburjs/Excalibur/issues/635
> [chore]: Add more action stories

- src/stories/Actions.stories.ts
- Add intro actions story so docs look better
- Split rotate story into rotate by and rotate to since they are separate actions
> [chore] Add actions intro story and split rotate story

- release.js
- renovate.json
Closes #1508
- Update the format of the 'chore' commit type to match the Conventional Commits specification
> chore: [#1508] Update Renovate/release commit format

- README.md
Revisit and clean up the language readability of the readme
> docs: Streamline language in the readme

- CHANGELOG.md
- package-lock.json
- package.json
- src/engine/Debug.ts
- src/engine/Input/Pointers.ts
- ~~[ ] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)~~
Upgrade to TypeScript 3.9.2
- Fix syntax in `Debug.ts`
- Workaround MS prefixed property in `Pointers.ts`
> chore: Upgrade to TypeScript 3.9.2

- CHANGELOG.md
- sandbox/src/game.ts
- src/engine/Resources/Texture.ts
- src/spec/TextureSpec.ts
Closes #1543
- Calls `complete()` callback on the super type that the loader listens too
- Adds a test
> fix: [#1543] Correct loading base64 string images

- .github/CODE_OF_CONDUCT.md
Update the Code of Conduct to align with
version 2.0 of the Contributor Covenant
Closes #1538
> docs: [#1538] Update our Code of Conduct

- src/spec/ColorBlindCorrectorSpec.ts
- src/spec/GifSpec.ts
- src/spec/SoundSpec.ts
Maybe Closes #1547 multiple `done()` possibilities cause issues for Jasmine, and cause tests to fail sometimes
- Fix Sound Tests
- Fix Gif Tests
- Fix Colorblind correction tests
> fix: [#1547] Flakey tests

- CHANGELOG.md
- src/engine/Actor.ts
- src/engine/Drawing/Animation.ts
- src/engine/Engine.ts
- src/spec/AnimationSpec.ts
Closes #1636
- Update animations in separate tick from draw()
- Add idempotency token to prevent the same animation from being updated multiple times per frame
- Added new tests
> fix: [#1636] Animation flicker on first frame

- src/engine/Resources/Sound/AudioInstance.ts
Guidance required for removal of the audio tag implementation.
As this is my first open source contribution, I am opening up this pull request by only making a few comments at the areas where I feel that the changes should be made.
- Not able to find any tests related to the `AudioTagInstance`
Related to  : [#1487](https://github.com/excaliburjs/Excalibur/issues/1487)
> chore: [#1487] Remove audio tag implementation

- CHANGELOG.md
- sandbox/src/game.ts
- sandbox/tests/collisionvelocity/vel.ts
- sandbox/tests/culling/culling.ts
- sandbox/tests/debug/boundingbox.ts
- sandbox/tests/group/group.ts
- sandbox/tests/physics/physics.ts
- sandbox/tests/physics/physics2.ts
- sandbox/tests/rotation/rotation.ts
- sandbox/tests/tilemap/tilemap.ts
- sandbox/tests/trigger/trigger.ts
- sandbox/tests/within/within.ts
- sandbox/tests/zoom/zoom.ts
- src/engine/Docs/Triggers.md
- src/engine/Engine.ts
- src/spec/EngineSpec.ts
- src/stories/utils.ts
Closes #1655
- change all direct modifications of `isDebug` to `showDebug` or `toggleDebug`
> refactor: [#1655] Change `isDebug` to `showDebug(toggle: boolean)`

- src/engine/Util/WebAudio.ts
Closes #1657
- Remove the use of WebAudio noteOn
> fix: [#1657] remove use of WebAudio noteOn

- README.md
Hi,
Highlighted the project's name and fixed a spelling mistake.
Great project! Peace!
> docs(readme): fix a typo

- deploy-docs.js
- package-lock.json
- package.json
- Use Octokit instead of Travis CI for triggering site builds
> chore: switch deploy-docs script to Octokit instead of Travis

- CHANGELOG.md
- sandbox/src/game.ts
- src/engine/Engine.ts
- src/engine/Screen.ts
- src/spec/ScreenSpec.ts
Renames new displaymodes to easier to understand names
> feat: Rename FullScreen -> Fit, Dynamic -> Fill

- CHANGELOG.md
- src/engine/EntityComponentSystem/Entity.ts
- src/spec/EntitySpec.ts
- Missing `removeTag()` method
- Update tests & changelog
> feat: Add missing removeTag method

- CHANGELOG.md
- src/engine/Drawing/CanvasDrawComponent.ts
- src/engine/Drawing/CanvasDrawingSystem.ts
- src/engine/EntityComponentSystem/Components/TransformComponent.ts
- src/engine/Graphics/GraphicsComponent.ts
- src/engine/Graphics/GraphicsSystem.ts
Namespaces built in component types with "ex." to avoid collisions with custom component types.
> feat: Namespace builtin components

- src/engine/Graphics/Raster.ts
- src/spec/GraphicsRasterSpec.ts
Closes #1897
- Width and Height include padding
- Update test to match
> fix: [#1897] Raster width/height include padding

- CHANGELOG.md
- src/engine/Loader.ts
- src/spec/LoaderSpec.ts
Closes #1854
- Stop propagation on play button click
> fix: #1854 play button click does not bubble into engine input

- CHANGELOG.md
- src/engine/Engine.ts
- src/spec/SceneSpec.ts
Closes #1850
- Call onActivate/onDeactivate with the correct arguments switch from call -> apply
- Add a test for this
> fix: [#1850] Fix Scene.onActivate/onDeactivate args

- CHANGELOG.md
- src/engine/Graphics/Animation.ts
- src/spec/GraphicsAnimationSpec.ts
Closes #1856
- Logs warning on invalid spritesheet indices
- Test
> feat: [#1856] Log warning on invalid spritesheet indices

- src/engine/Polyfill.ts
- [NA] :pushpin: issue exists in github for these changes
- [NA] :page_facing_up: changelog entry added (or not needed)
Reduce required polyfills to array.sort (ECS relies on the sort being stable) and Object.keys
> chore: Reduce polyfills

- CHANGELOG.md
- sandbox/tests/physics/fastphysics.ts
- sandbox/tests/physics/physics.ts
- sandbox/tests/within/within.ts
- src/engine/Actor.ts
- src/engine/Collision/BodyComponent.ts
- src/engine/Collision/ColliderComponent.ts
- src/engine/Collision/CollisionSystem.ts
- src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
- src/engine/Collision/Shapes/Collider.ts
- src/engine/Collision/Shapes/CollisionJumpTable.ts
- src/engine/Collision/Shapes/Edge.ts
- src/engine/Collision/Solver/RealisticSolver.ts
- src/engine/Debug/DebugSystem.ts
- src/engine/Graphics/Circle.ts
- src/spec/ActorSpec.ts
- src/spec/CollisionContactSpec.ts
- src/spec/CollisionShapeSpec.ts
- src/spec/CollisionSpec.ts
- src/spec/DynamicTreeBroadphaseSpec.ts
- src/spec/GraphicsCircleSpec.ts
- Fix issue with the Edge collider where it wasn't working in any collisions
- Tweak the collider api to avoid the awkward `collider.collider` with `collider.get()`
- Add convenience radius arg to Actor constructor to build an actor with a circle collider
> fix: Edge collider not working + Tweak collider component + Actor radius ctor arg

- .github/workflows/build.yml
- .gitmodules
- package-lock.json
- package.json
- scripts/apidocs.js
- src/engine/Actions/Index.ts
- src/engine/Actor.ts
- src/engine/Collision/BodyComponent.ts
- src/engine/Collision/Physics.ts
- src/engine/Collision/Side.ts
- src/engine/Drawing/Animation.ts
- src/engine/Drawing/CanvasDrawComponent.ts
- src/engine/Drawing/Polygon.ts
- src/engine/Drawing/Sprite.ts
- src/engine/Drawing/SpriteEffects.ts
- src/engine/Engine.ts
- src/engine/EntityComponentSystem/Components/TransformComponent.ts
- src/engine/EntityComponentSystem/index.ts
- src/engine/Graphics/Animation.ts
- src/engine/Graphics/SpriteSheet.ts
- src/engine/Input/CapturePointerConfig.ts
- src/engine/Input/Index.ts
- src/engine/Interfaces/Index.ts
- src/engine/Label.ts
- src/engine/Math/Random.ts
- src/engine/Traits/CapturePointer.ts
- src/engine/Traits/Index.ts
- src/engine/Util/Index.ts
- src/engine/Util/Observable.ts
- src/engine/index.ts
> chore: Update to latest TypeDoc :tada: + Update Documentation

- CHANGELOG.md
- sandbox/src/game.ts
- sandbox/tests/coordinates/coordinates.ts
- sandbox/tests/input/iframe.ts
- sandbox/tests/input/keyboard.ts
- sandbox/tests/label/fonts.ts
- sandbox/tests/label/label.ts
- sandbox/tests/rotation/rotation.ts
- src/engine/Label.ts
- src/spec/LabelSpec.ts
- Update Label to use the new option bag constructor
> feat: Update Label constructor to option bag

- CHANGELOG.md
- src/engine/Graphics/GraphicsComponent.ts
- src/spec/GraphicsComponentSpec.ts
Closes #2044
- Add Current Graphics Keys to GraphicsComponent #2044
> feat: [#2044] Add Current Graphics Keys to GraphicsComponent

- CHANGELOG.md
- Fix broken links to several previous release issue lists
- General cleanup
> chore: Update changelog for 0.25.1 release

- renovate.json
At the moment, we need to keep typedoc in-sync between this repo and https://github.com/excaliburjs/excaliburjs.github.io
At a later date, we should be able to refactor this workflow so docs repo can use the typedoc version installed in this repo instead.
- Disable automerge for typedoc upgrades
> chore(renovate): do not automerge typedoc

- package-lock.json
- package.json
Reverts excaliburjs/Excalibur#2137
> chore(deps): revert "Update dependency typedoc to v0.22.10"

- README.md
Closes #2109 
- Replace the broken features link with the new one in the README.md
> Fix: [#2109] Replace the features link

- CHANGELOG.md
- sandbox/tests/side-collision/index.html
- sandbox/tests/side-collision/index.ts
- sandbox/tests/side-collision2/index.html
- sandbox/tests/side-collision2/index.ts
- sandbox/tests/sound/sound.ts
- src/engine/Collision/Solver/ArcadeSolver.ts
- src/engine/Collision/Solver/RealisticSolver.ts
- src/engine/Collision/Solver/Solver.ts
- src/spec/ArcadeSolverSpec.ts
- src/spec/CollisionSpec.ts
Closes #2344 #2343
This PR changes how the `ArcadeSolver` solves collisions to avoid errant collisions on seams in geometry. The idea behind this fix is to sort the collision contacts by distance. Additionally if a contact has no more overlap during processing they are now discarded so errant collisions are even evaluated.
Note there are no more left right collisions in the console compared to the [sandbox](https://8wf42u.csb.app/)
This PR also fixes #2343 by ignoring "divergent contacts" which are when the underlying body's are already moving away from the contact, so no velocity adjustment is needed. This was noticeable when clipping corners, but the object was already moving out of the collision.
TODO: 
- Change the `Solver` …
> fix: [#2344] [#2343] Arcade Solver sorts contacts by distance and ignores diverging contacts

- .vscode/settings.json
Closes #2376
- updates eslint config `vscode/settings.json`to prevent error messages
> chore: [#2376] update eslint config in vscode settings

- src/engine/Actor.ts
- src/spec/ActorSpec.ts
- [NA] :page_facing_up: changelog entry added (or not needed)
Related https://github.com/excaliburjs/Excalibur/issues/2419#issuecomment-1189808274
- Update log message to be more helpful
> fix: Update entity not in scene warning

- CHANGELOG.md
- src/engine/EntityComponentSystem/Entity.ts
- src/engine/EntityComponentSystem/EntityManager.ts
- src/engine/Scene.ts
- src/spec/EntitySpec.ts
Closes #2455 
Closes #2456 
- Unparent children when `.kill()` is called
- Fix issue in `.removeAllChildren()` where the delete would modify the collection while iterating
> fix: [#2455][#2456] Entity removing children bugs

- package-lock.json
- package.json
- scripts/apidocs.js
Closes #
- Update to typedoc 0.23.20
**!! DO NOT MERGE !!**
Until I have the site ready as well. This should merge first, which will break the site build. Then the site PR can re-run its checks and it should work. This has been tested locally between the two.
> chore: update typedoc to 0.23

- CHANGELOG.md
- sandbox/index.html
- sandbox/tests/clonebehavior/index.html
- sandbox/tests/clonebehavior/index.ts
- src/engine/Collision/ColliderComponent.ts
- src/engine/Graphics/GraphicsComponent.ts
- src/spec/ColliderComponentSpec.ts
- src/spec/ComponentSpec.ts
- src/spec/GraphicsComponentSpec.ts
Closes #2575 
- Update Graphics layer cloning to clone individual graphics
- Update Collider Component cloning to clone stored colliders
> [#2575] fix actor clone

- src/engine/EventEmitter.ts
Closes https://github.com/excaliburjs/Excalibur/pull/2666/files#r1248739822
Minor refactor
> refact(engine/EventEmitter): minor refact

- CHANGELOG.md
- sandbox/tests/linebounds/index.html
- sandbox/tests/linebounds/index.ts
- src/engine/Graphics/Line.ts
- src/spec/LineSpec.ts
Closes #2773
- Update bounds calculation on Lines to be correct from the geometry
- Fix tests
> fix: [#2773] Line bounds are now correct

- CHANGELOG.md
- src/engine/EntityComponentSystem/EntityManager.ts
- src/engine/EntityComponentSystem/Query.ts
- src/engine/EntityComponentSystem/SystemManager.ts
- src/engine/Scene.ts
Fixes some Excalibur `.clear()` implementations that were problematic. Walking backwards through the collection prevents the issue where removing and walking forward causes the length of the collection to change and shift during iteration.
> fix: clear implementations

- CHANGELOG.md
- src/engine/Actor.ts
- src/engine/Camera.ts
- src/engine/Engine.ts
- src/engine/EntityComponentSystem/Entity.ts
- src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
- src/engine/Interfaces/LifecycleEvents.ts
- src/engine/Loader.ts
- src/engine/Particles.ts
- src/engine/Scene.ts
- src/engine/tsconfig.json
> fix: [#2855] Remove dunder prefixed parameters

- CHANGELOG.md
- src/engine/Graphics/GraphicsSystem.ts
- src/spec/ActorSpec.ts
> fix: [#2854] Actor pre/post draw events fixed

- CHANGELOG.md
- src/engine/TileMap/IsometricMap.ts
Add missing arbitrary data storage in `IsometricTile`s that exists on normal `Tile`s
> feat: Add IsometricTile.data storage

- CHANGELOG.md
- src/engine/Input/PointerComponent.ts
Closes #
- change 1
- change 2
> change: Pointers will use graphics bounds by default

- site/docs/02-fundamentals/04-cameras.mdx
- site/docs/05-entity-component-system/05-entity-component-system.mdx
- site/docs/10-physics/08-colliders.mdx
- site/docs/11-input/10.3-pointer.mdx
- site/docs/11-input/10.4-gamepad.mdx
- site/docusaurus.config.ts
- src/engine/Input/Index.ts
- src/engine/index.ts
Closes #
- fix: symbol link handling namespaces/fully qualified symbols
- docs: Better Mouse and Touch (formerly, "Pointers") docs using Twoslash snippets and updated for new API
> docs: Fix symbol linking + Pointer docs improvements

- site/src/pages/showcase/_data.ts
> refactor(showcase): update retroski demo url

- CHANGELOG.md
- sandbox/tests/router/index.ts
- src/engine/Director/CrossFade.ts
- src/engine/Director/DefaultLoader.ts
- src/engine/Director/Director.ts
- src/engine/Director/FadeInOut.ts
- src/engine/Director/Transition.ts
- src/engine/Screen.ts
- src/spec/DirectorSpec.ts
- src/spec/FadeInOutSpec.ts
- Fixed issue where start transition did not work properly if deferred
- Fixed issue where transitions did not cover the whole screen if camera was zoomed
> fix: Transition bug when camera is zoomed

- site/package-lock.json
Reverts excaliburjs/Excalibur#2953
> revert: "chore: Update dependency docusaurus-plugin-typedoc-api to v4.2.0"

- src/engine/Math/vector.ts
Only a comment/documentation for vector.rotate() is corrected, no changes in code. 
Closes #2975
- Comment for Vector.rotate()
> chore: Correct the doc for vector.rotate

- site/docs/05-entity-component-system/05.3-systems.mdx
Closes #
- change 1
- change 2
> Typo fix: post instead of pre.

- site/docs/08-tile-maps/07-tilemap.mdx
kenny changed to kenney (url changed to kenney.nl)
> Update 07-tilemap.mdx kenny.nl url changed to kenney.nl

- site/blog/2024-05-19-pathfiinding-part1/pathfindingpart1.md
update link to Part 2 in Part 1 pathfinding blog
> blog: update link in part 1

- src/engine/Collision/BoundingBox.ts
The `if` didn't seem that useful anymore
> Simplified contains BoundingBox code

- CHANGELOG.md
- src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
- src/engine/Graphics/Context/state-stack.ts
- src/engine/Graphics/Context/transform-stack.ts
- src/engine/Graphics/GraphicsComponent.ts
- src/engine/Math/affine-matrix.ts
- src/engine/Math/transform.ts
- src/engine/Math/watch-vector.ts
- src/engine/Util/RentalPool.ts
- src/spec/CollisionShapeSpec.ts
- src/spec/ScreenElementSpec.ts
This PR takes a stab at a lot of the hot path allocations in excalibur improving performance significantly (numbers will be forthcoming with the new broadphase updates)
- New `RentalPool` type for sparse object pooling
- Perf improvements: Hot path allocations
* Reduce State/Transform stack hot path allocations in graphics context
* Reduce Transform allocations
* Reduce AffineMatrix allocations
> perf: Reduce allocations on the hot path

- src/engine/Color.ts
Add named colors to Color.ts (Brown, Teal, Pink, Purple)
> Add more common colors

- src/engine/Actions/Action/Flash.ts
- src/engine/Actions/Index.ts
created Flash.ts and updated index.ts in the Action directory
> feat: Flash Action

- CHANGELOG.md
- src/engine/Resources/Gif.ts
- src/engine/Resources/Sound/AudioContext.ts
- src/engine/Resources/Sound/Sound.ts
- src/engine/Resources/tsconfig.json
- src/engine/TileMap/TileMap.ts
> fix: [#3167] Increase strictness in Resource types

- site/docs/10-physics/08-a-physics.mdx
- src/engine/Collision/BodyComponent.ts
- [change 1](docs: Add limitations of SolverStrategy.Arcade)
> docs: Add limitations of SolverStrategy.Arcade

- site/package-lock.json
- site/package.json
Reverts excaliburjs/Excalibur#3196
> revert "chore: Update docusaurus monorepo to v3.5.2"

- src/engine/Camera.ts
- src/engine/Engine.ts
- src/engine/Graphics/GraphicsSystem.ts
Closes #
- change 1
- change 2
> feat: Add alias fixed update timestep

- site/docs/02-fundamentals/03-actors.mdx
> Probably a typo in explaining actor children 

- CHANGELOG.md
- src/engine/EntityComponentSystem/Entity.ts
Perf improvement to retrieving components with `ex.Entity.get()` which widely improves engine performance
Concept by @mattjennings many thanks!
> perf: Improve ex.Entity.get(...)

- sandbox/src/game.ts
- src/engine/Actions/Action/Blink.ts
- src/engine/Actions/Action/Flash.ts
- src/engine/Actor.ts
- src/engine/Collision/BodyComponent.ts
- src/engine/Collision/ColliderComponent.ts
- src/engine/Collision/CollisionSystem.ts
- src/engine/Collision/Detection/CollisionContact.ts
- src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
- src/engine/Collision/Detection/Pair.ts
- src/engine/Collision/Detection/SparseHashGridCollisionProcessor.ts
- src/engine/Collision/MotionSystem.ts
- src/engine/Debug/DebugSystem.ts
- src/engine/Engine.ts
- src/engine/EntityComponentSystem/Entity.ts
- src/engine/EntityComponentSystem/EntityManager.ts
- src/engine/Graphics/GraphicsComponent.ts
- src/engine/Graphics/GraphicsSystem.ts
- src/engine/Input/PointerAbstraction.ts
- src/engine/Input/PointerSystem.ts
- src/engine/Particles/Particles.ts
- src/engine/Scene.ts
- src/engine/Screen.ts
- src/engine/TileMap/IsometricMap.ts
- src/engine/Trigger.ts
- src/engine/Util/Util.ts
- src/spec/CurveActionSpec.ts
Closes #
- change 1
- change 2
> chore: update api with new deprecations

- site/package-lock.json
- site/package.json
Reverts excaliburjs/Excalibur#3304
> Revert "chore: Update docusaurus monorepo to v3.6.3"

- site/docs/00-tutorial/03-step-bird-and-ground.mdx
- site/docs/00-tutorial/06-step-refactor-to-scene.mdx
- site/docs/00-tutorial/10-step-game-over.mdx
- site/docs/00-tutorial/11-step-images-graphics.mdx
- site/docs/00-tutorial/12-step-bird-graphics.mdx
- site/docs/00-tutorial/14-step-ground-graphics.mdx
- site/docs/00-tutorial/15-step-sound-music.mdx
- Errors fixed in example code
- More context added in fragment of code
> [#3320] Fix details in Tutorial - Building Flappy Bird

- site/src/pages/showcase/_data.ts
Hey,
Didn't create an issue for this showcase update.
Hope it's still OK.
Closes #
> Update site showcase RetroSki url, title & description

- site/package-lock.json
- site/package.json
Reverts excaliburjs/Excalibur#3339
> Revert "chore: Update docusaurus monorepo to v3.7.0"

- src/engine/TileMap/TileMap.ts
Closes #
- change 1
- change 2
> fix: TileMap meshes properly when transform changes

- site/docs/03-screen-viewport/screens-display-modes.mdx
fixed small typo in FitScreenAndFill
> DOCS: Update screens-display-modes.mdx

- site/package-lock.json
- site/package.json
Reverts excaliburjs/Excalibur#3402
> Revert "chore: Update docusaurus monorepo to v3.8.0"

- CHANGELOG.md
- site/package-lock.json
- site/package.json
- site/src/pages/premium-support/index.js
- src/engine/Collision/Integrator.ts
- src/engine/Graphics/GraphicsComponent.ts
- src/spec/vitest/ActorSpec.ts
=== :clipboard: PR Checklist :clipboard: ===
Closes #3424 
- Adds `maxVel` attribute to `MotionComponent`, which clamps velocity on separated X and Y axes
> #3424 feat: Add maxVel to MotionComponent

- site/docs/07-actions/06.5-actions-meet.mdx
- src/engine/Actions/Action/Meet.ts
- src/engine/Actions/ActionContext.ts
##Changes
in Meet.ts
- added private _tolerance=1;
- added optional tolerance to the constructor params
- in constructor added test for tolerance, in order to overwrite it
- in isComplete() changed 1 to this._tolerance
> updated Meet action to add tolerance

- CHANGELOG.md
- sandbox/tests/transition/index.ts
- src/engine/Director/Director.ts
- src/engine/Interfaces/LifecycleEvents.ts
- src/engine/Scene.ts
- src/spec/vitest/SceneSpec.ts
Adds `onDeactivate` data to the next `SceneActivateContext` `previousSceneData` property
> feat: Implement Scene deactivation data passing

- CHANGELOG.md
- sandbox/tests/input/pointer.ts
- src/engine/Collision/CollisionSystem.ts
- src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
- src/engine/Collision/Detection/SparseHashGridCollisionProcessor.ts
Closes #3412 
Fixes this coupling that prevents pointers from working on Entities that
do not have a body/motion component
- Remove the `BodyComponent` from the CollisionSystem query, it was actually unnecessary coupling! 
- If the body component is not present no resolution behavior happens, but collision events should still fire
> fix: [#3412] collider body coupling

- CHANGELOG.md
- sandbox/tests/onpreload/index.html
- sandbox/tests/onpreload/index.ts
- src/engine/Director/Director.ts
- src/engine/Scene.ts
closes https://github.com/excaliburjs/Excalibur/issues/3452
> fix: [#3452] Initial scene respects onPreLoad 

- site/docs/09-math/07-graph.mdx
- src/engine/Math/graph.ts
- src/engine/Math/index.ts
- src/spec/vitest/GraphSpec.ts
Graph Module
Files changed
Docs page: 07-graph.mdx
Code Module: /Math/graph.ts
index export: /Math/index.ts
Test file: /spec/vitest/GraphSpec.ts
> Graph Module

- site/docs/02-fundamentals/examples/scene-crossfade.ts
* Change game.goto to game.goToScene
* Example now runs correctly without runtime errors
> Correct scene-crossfade.ts example

- site/docs/04-graphics/04.2-material.mdx
made the additional texture a little more explicit
> [DOC tweak in material documentation] Update 04.2-material.mdx
