excaliburjs/Excalibur

src/engine/Actor.ts
src/engine/Scene.ts
src/engine/Util/SortedList.ts
src/spec/SortedListSpec.ts

I believe this is the simplest way to resolve this issue for now. We'll revisit this when the self-balancing implementation is built.

Fixes #433 actors not being cleaned up in draw tree

---

src/engine/Actor.ts
src/spec/ActorSpec.ts

actor.getCenter() was not properly accounting for the anchor of an actor
to be anywhere other than the top left corner

close #438 fixing actor.getCenter()

---

src/engine/Actions/ActionContext.ts
src/spec/ActorSpec.ts

When the rotation api for Actors was changed from Actor.rotateTo /
Actor.rotateBy to Actor.actions.rotateTo / Actor.actions.rotateBy,
the rotation type was forgotten on the new method signatures.
closes #575

Fix rotation API to re-include rotation types

---

docs/source/quickstart.rst

The fiddle was not correct in our documentation.
This updates the fiddle to match the fix in #650

Fix fiddle for #650

---

docs/source/quickstart.rst

The paddle is pushed down by the ball when the collision occur.
- ex.CollisionType.Fixed

quickstart tutorial : Collision Fixed instead of Active

---

.vscode/settings.json
GruntFile.js
package.json
src/spec/support/sourcemaps.js
tslint/tslint.json

- Add TS source map support for test failures
- Fix TSLint integration with VS Code and upgrade grunt plugin
You can now use TSLint VS code extension! And when tests fail it will pinpoint the Typescript source line.

Add Node.js sourcemap support and fix TSLint for VS Code

---

CHANGELOG.md
GruntFile.js
sandbox/web/src/game.js
sandbox/web/src/game.ts
src/engine/Actor.ts
src/engine/Collision/Body.ts
src/engine/Collision/CollisionContact.ts
src/engine/Collision/DynamicTree.ts
src/engine/Collision/DynamicTreeCollisionBroadphase.ts
src/engine/Collision/ICollisionResolver.ts
src/engine/Collision/NaiveCollisionBroadphase.ts
src/engine/Physics.ts
src/engine/Scene.ts
src/spec/ActorSpec.ts
src/spec/DynamicTreeBroadphaseSpec.ts
src/spec/Mocks.ts

Closes #643
Pointer events were being triggered multiple times per frame. This was a result of the physics doing multiple passes on each actor by calling the update function multiple times.
This fixes the issue by refactoring the integration step of actor update out of actor update, so that it can be called multiple times for collision passes and not affect other operations that expect update to be called once per frame.
Additionally, this uncovered a bug in Actor.on('pointerup') opt-in which was subsequently fixed.

[#643] Fix Actor updates happening more than once per frame

---

.travis.yml
GruntFile.js
package.json

Closes #621 
This includes a new grunt plugin for manipulating package.json files to help on 2 fronts
1. Only needing to update the package.json version in 1 place (main excalibur repo package.json)
2. Automate pre-release npm package deployments in the form exVersion-alpha.travisBuildNumber+commitHash (for example a plausible package version would be 0.7.1-alpha.12+6feca33)
This PR needs to be merged into master before the travis automation can be verified, bummer I know 😭  Once we know that the excalibur-dist repo is being updated appropriately with the correct package.json, the automagic publish to npm job can be activated.
Ultimately I would like to also automate the cutting of release NPM packages when a release is tagged (see https://docs.travis-ci.com/user/deployment/npm/) but I …

[#621] Automate npm pre-release versioning

---

CHANGELOG.md
src/engine/Algebra.ts
src/spec/AlgebraSpec.ts

Closes #663
- Add `Vector.magnitude` alias that calls `Vector.distance()`
- Clarify docs on `Vector.distance()`

[#663] Add alias `magnitude` to `Vector`

---

CHANGELOG.md
src/engine/Algebra.ts
src/spec/AlgebraSpec.ts

Closes #662
- `ex.Line.slope` for the raw slope (m) value
- `ex.Line.intercept` for the Y intercept (b) value
- `ex.Line.findPoint(x?, y?)` to find a point given an X or a Y value
- `ex.Line.hasPoint(x, y, threshold)` to determine if given point lies on the line

[#662] Add Line math methods

---

CHANGELOG.md
src/engine/Actor.ts
src/spec/ActorSpec.ts

Closes #666 
- Fix `oldVel` value being set to the current frame's value due to `addEqual` mutator method
- Fix `oldPos` not being set at all
Two issues I discovered:
1. `oldVel` was wrong, it was being set to the current frame's value
2. `oldVel` (and now `oldPos`) are being set in the `integrate()` method of Actor but that method can be called multiple times per update, hence oldVel and oldPos are probably not accurate for use within an update loop especially if they are supposed to represent the previous frame values.

[#666] Fix `oldVel` and `oldPos` values being updated

---

CHANGELOG.md
src/engine/Label.ts

Closes #679 
- fix `Label#getTextWidth` so it returns proper number
- introduce protected readonly `_fontString` property, which properly combines fontFamily with fontSize and is used in `_fontDraw` and `getTextWidth`.
Basically, this PR changes method so it takes into account not only fontFamily, but fontSize too.

Fix Label#getTextWidth returns incorrect result

---

CHANGELOG.md
src/engine/Promises.ts
src/spec/PromiseSpec.ts

Closes #501
- Add `ex.Promise.resolve`
- Add `ex.Promise.reject`
- Deprecated `ex.Promise.wrap`
We need to add an `onRejected` callback to `then` to match Promise A+ spec.

[#501] Add Promise.resolve/reject methods

---

CHANGELOG.md
src/engine/Drawing/SpriteEffects.ts

Closes #687 
- Change Effects.Opacity so it calculates pixel's opacity relative to current opacity value, not fixed number.

Fix Effects.Opacity invalid opacity handling

---

src/engine/Physics.ts

- Fix typo in Physics docs, there's no `edge` variable around, definitely meant `ground`

Fix typo in Physics docs (egde -> ground)

---

src/engine/Actor.ts
src/engine/Drawing/Sprite.ts

- In `Actor`, don't reapply effects to drawing in `update` method, do it only in `draw` and if `frames` or `opacity` was changed
- In `Sprite`, always set `_effectsDirty` flag after effects were applied
- Few minor changes, like don't calculate same value twice in same method
It's my attempt to improve things on issue #481. It doesn't close issue completely because source of unnecessary calls to `Sprite#_loadPixels` remains mystery to me, but I was able to reduce amount of `_applyEffects` calls.
I can miss some effects' use cases (although sandbox tests seemed working), so please review this carefully.

Minimize Sprite#_applyEffects calls count

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Collision/BoundingBox.ts
src/spec/ActorSpec.ts

This pull request fixes an issue that was brought up on the google groups where rotated and scaled width and height could not be easily calculated, and the `actor.getWidth()` and `actor.getHeight()` were misleading.
@excaliburjs/core-contributers Before we merge this PR, I think we should have a discussion about `actor.getWidth()` and `actor.getHeight()` should they continue to operate without knowledge of rotation? is there a compelling reason to not just report the actual width and height of the bouding box? Please comment.
Closes #692 
- Add a static method for creating bounding boxes `ex.BoundingBox.fromPoints`
- Add a method for rotating bounding boxes `ex.BoundingBox.rotate`
- `actor.getBounds()` and `actor.getRelativeBounds()` now always return the correct bounds regardless of …

[#692] Actor Bounding Boxes Include Rotation and Scale

---

docs/source/installation.rst

Added #675 info to official docs to help assist people in referencing Ex via import syntax until #606 is done

Add import syntax docs

---

GruntFile.js
appveyor.yml
docs/source/unstable.rst

Previously, we had to update a setting in the Appveyor UI to hold the current Excalibur version, making releases difficult.
I've updated the appveyor build to now just use the package.json version, and append the build number. This eliminates any dependency on anything inside of Appveyor.
- Remove dependency on Appveyor version environment variable
- Update Unstable Builds documentation to add npm/bower information

Fix Appveyor versioning and update unstable docs

---

src/engine/Engine.ts
src/spec/AlgebraSpec.ts

Closes #711
- Remove direct references to deprecated context smoothing attributes
- Added dynamic setting of context smoothing attributes by existence

[#711] Removing reference to setting deprecated value

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Util/Detector.ts

Closes #707 
- Added singleton browser feature support matrix into Detector.ts
- Added debug step in Engine.ts to log feature support matrix
- Added a getter to access the current support matrix from consuming modules: `Detector.getBrowserFeatures()`
For future reference, any additional features that are desired to show up in this log statement need two things:
1.  Add the IIFE to assign support value in `Detector._loadBrowserFeatures()`
2.  Add the human readable label to the features map in `Detector.logBrowserFeatures()`
As it stands, if debugging is enabled, here is the output to the console:
Feedback encouraged!

[#707] Add report for browser feature support

---

CHANGELOG.md
GruntFile.js
src/engine/Docs/Actions.md
src/engine/Docs/Animations.md
src/engine/Docs/Labels.md
src/engine/Docs/TileMaps.md
src/engine/Engine.ts
src/engine/Label.ts
src/engine/Promises.ts
src/engine/Util/Decorators.ts
src/engine/tsconfig.json
src/spec/DecoratorSpec.ts
src/spec/tsconfig.json

Closes #684 
- Implement `@obsolete` decorator with the ability to pass a custom message and/or suggest a suitable alternative method
- Mark `exPromise.wrap` and `exEngine.fps` as `@obsolete`
- Update grunt build and tsconfig.json to include the `experimentalDecorators` flag
One thing to note, is that the decorator api **only works on functions/getters/setters** so if you want to make a particular property obsolete, you'll need to refactor it into getter/setter and decorate accordingly.
This is what shows up in the console when attempting to use a decorated method.

[#684] Implement Obsolete Decorator

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/engine/Drawing/Sprite.ts

Closes #726
- Update to TS 2.1.4
- Fix bug in `Sprite.debugDraw`

[#726] Update to TypeScript 2.1.4

---

src/engine/Engine.ts
src/engine/Math/Random.ts
src/spec/RandomSpec.ts

Closes #538 
- Implements a seeded random utility in Excalibur called `ex.Random` using the popular Mersenne-Twister algorithm documented [here](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html) and [here](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/emt.html)
- Added new utilities for random
* Random in range (`ex.Random.floating()`/`ex.Random.integer()`), 
* Coin-tosses with variable outcomes `ex.Random.bool()`
* Pick-one `ex.Random.pickOne(array)`
* Pick-set `ex.Random.pickSet(array, numPicks)`
* Dice roll helpers for d4, d6, d8, d10, d12, and d20
- Tests for the random features included
Additionally I have compared this implementation to the native C implementation done by the people who originally proposed the paper and it returns the same values for a seeded …

[#538] Implement a better seeded Random 

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Scene.ts
src/engine/TileMap.ts
src/spec/SceneSpec.ts

Closes #584
- Fixed order of processing of Timers in Scene to support processing Actors/UIActors/TileMaps added during callback
- Added `preupdate`, `postupdate`, `predraw`, and `postdraw` events to TileMap for testing

[#584] Fix order of timer processing in Scene

---

CHANGELOG.md
src/engine/Engine.ts
src/spec/EngineSpec.ts

Closes #750 
- Added a function isPaused to check the running status of Engine into Engine.ts

[#750] Add Engine's Running Status Check

---

CHANGELOG.md
src/engine/Engine.ts
src/spec/EngineSpec.ts

Helper method getWorldBounds was added to the engine class.
It calculates the top left corner of the screen and the
bottom right corner of the screen and wraps them in a
BoundingBox. One test added to test this new method.
Closes #729
- Added getWorldBounds helper method to Engine class
- Added test for getWorldBounds

[#729] Added getWorldBounds method to Engine

---

CHANGELOG.md
src/engine/Engine.ts
src/spec/EngineSpec.ts

Closes #744
- Added predraw and postdraw events to Engine class

Add pre and post draw events [#744]

---

.travis.yml
GruntFile.js

Related #777 
- Install SASS gem
- Run API docs build at end of build

Fix API docs build

---

docs/source/quickstart.rst

Closes #790 
- Corrected 3 instances of `game.getHeight()` or 'game.getWidth()` to `game.getDrawHeight()` or `game.getDrawWidth()` in the [Getting Started guide](http://docs.excaliburjs.com/en/latest/quickstart.html) per latest naming in v 0.10.0
##Note:
This change corrects files in github, but the old verbiage is still used on the [JS Fiddle site](http://jsfiddle.net/excaliburjs/6Ay9S/39/?utm_source=website&utm_medium=embed&utm_campaign=6Ay9S). I am unsure if it is desired to update the [code being fed to JS Fiddle](https://rawgit.com/excaliburjs/excalibur-dist/v0.7.1/dist/excalibur.js) to the latest version.

Correct method name in documentation

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/scene/display-mode-position.css
sandbox/tests/scene/display-mode-position.html
sandbox/tests/scene/display-mode-position.ts
src/engine/Docs/Engine.md
src/engine/Engine.ts
src/spec/EngineSpec.ts
src/spec/TestUtils.ts

Closes #781 
- Added another DisplayMode option: `DisplayMode.Position`. When this is selected as the displayMode type, the user must specify a new `position` option
- Added a new Interface `AbsolutePosition` which can describe the `position` option. A `string` can also describe `position`
I've written some Jasmine tests for this issue, as well as made sure that this didn't break any tests. (there were 8 tests that were failing before I implemented my changes, looks like HTML property changing tests).
I've updated the docs in the repo, but it may be good to document on [the external docs site](https://excaliburjs.com/docs/api/v0.10.0/index.html). I'm happy to do that if need be!
Note also that I don't believe the Engine display mode was reliably being set before. There were references to …

Add window positioning as an Engine option

---

src/engine/Docs/Actors.md

There was a typo in the canvas rendering context argument of the `draw` method

Fix typo in Actors.md

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/audio/setvolume.html
sandbox/tests/audio/setvolume.ts
src/engine/Docs/Sounds.md
src/engine/Resources/Sound.ts
src/spec/SoundSpec.ts

Closes #801 
- Added optional volume argument to `Sound.play(volume?: number)`, which will play the Audio file
+at anywhere from mute (`volume` is 0.0) to full volume (`volume` is 1.0).

[#801] Add per-play sound volume option

---

sandbox/tests/input/keyboard.html
sandbox/tests/input/pointer.html
src/engine/Engine.ts
src/engine/Input/Keyboard.ts
src/engine/Input/Pointer.ts

I started to write tests for Pointer, but quickly realized that the init function for the Pointers class was not able to easily be mocked.
I changed it to match the same method that Keyboard uses, which is to pass in the "target" instead of an option to define what it is binding to.

Changed pointer initialization to match same initialization as keyboard in order to make mocking for tests possible.

---

src/spec/AlgebraSpec.ts

Closes #817
- replaced 'lenght' with 'length' in a test spec in AlgebraSpec.ts - I did not make a note of this in the ChangeLog, I assume that's okay.

[#817] Fix typo in AlgebraSpec.ts

---

CHANGELOG.md
src/engine/Scene.ts
src/engine/Timer.ts
src/spec/TimerSpec.ts

One caveat to this PR is that reseting timers violated a previous assumption that timers were no longer needed after they fired once. But now that we can reset timers, we don't know if the user meant to be done permanently with a timer. This means that timers have the potential to hang around in the scene if not cleaned up over time with `.cancel()` 
Closes #566
- Implement `ex.Timer.reset` that allows for reuse of timers, reset also allows a safe way to change the interval of a timer
- Added unit tests checking both finite and repeating timers

[#566] Implement safe timer reset method

---

src/spec/LabelSpec.ts

There is a rendering discrepancy on a recent version of Windows that causes these tests to fail locally.
Note: This is a temporary skip of these tests to prevent confusion for new contributors when they run the tests locally. 
Related issues:  #833

Skip font-based label tests

---

version.js

Related to #777
This will accomplish ensuring the dist files have the correct tagged version for release builds.
- Use Travis Git tag as version if available

Use Travis Git tag version if available

---

docs/source/quickstart.rst

The getting started docs were not updated after `ex.CollisionType.Elastic` was removed, and neither was the fiddle.
This came to our attention after a post on the forum: https://groups.google.com/forum/#!topic/excaliburjs/8vt1jwoW85c
- Latest fiddle has been updated with v0.12.0 release  https://jsfiddle.net/excaliburjs/6Ay9S/
- Updated getting started documentation with changes

Fix getting started docs

---

CHANGELOG.md
src/engine/Actor.ts
src/spec/ActionSpec.ts

Closes #840 
- Made `color` on `Actor` have a getter/setter, which implicitly clones the color value when set

[#840] Implicitly clone a color when setting it

---

CHANGELOG.md
src/engine/Input/Pointer.ts

Closes #612 
- mark `x` and `y` parameters as obsolete
- add `pos` Vector that will replace `x` and `y`

[#612] Add position vector to PointerEvent

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Class.ts
src/engine/EventDispatcher.ts
src/engine/Interfaces/IEvented.ts
src/spec/EventSpec.ts

Closes #745
- Implements a new way to listen to events `.once(...)` and then unsubscribe
- Additional tests

[#745] Implement `once` event listener

---

CHANGELOG.md
package-lock.json
sandbox/tests/physics/physics.ts
src/engine/Algebra.ts
src/engine/Collision/CollisionJumpTable.ts
src/engine/Collision/PolygonArea.ts
src/spec/AlgebraSpec.ts
src/spec/CollisionAreaSpec.ts

Closes #703
- Corrects odd behavior shown in the bug
- Added tests around fix and new utilities
- Implement new utilities to assist in collision calculations
* `Line.normal` calculates the positive normal of the line
* `Line.distanceToPoint` calculates the perpendicular distance from a point to a line
* `PolygonArea.getClosestFace` finds the face with the lowest perpendicular distance to the point

[#703] Fix polygon edge collision

---

CHANGELOG.md
sandbox/index.html
sandbox/src/game.ts
sandbox/tests/camera/strategy.html
sandbox/tests/camera/strategy.ts
src/engine/Camera.ts
src/engine/Docs/Cameras.md
src/engine/Scene.ts
src/spec/CameraSpec.ts

Closes #445
TODOS before merge: 
- Implements new strategy pattern with some built-in strategies
- Updates documentation
- Deprecates `ex.LockedCamera` and `ex.SideCamera`

[#445] Implement camera strategies

---

src/engine/Resources/Sound.ts

Closes #920
- Use `GainNode.gain.setTargetAtTime` as recommended instead of setting `GainNode.gain.value` directly where possible

[#920] Use setTargetAtTime to set volume for Sound

---

.travis.yml

Currently CI is broken on master
This corrects it given the new documentation
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode
https://travis-ci.org/excaliburjs/Excalibur/builds/327439382

[chore] Fix ci in new travis env

---

CHANGELOG.md
sandbox/tests/input/pointer.html
sandbox/tests/input/pointer.ts
src/engine/Actor.ts
src/engine/Algebra.ts
src/engine/Events.ts
src/engine/Input/Pointer.ts
src/engine/Traits/CapturePointer.ts
src/spec/ActorSpec.ts

Adds several events for dragging of actors, this will allow developers to
implemented their own style of 'drag and drop', such as 'pulling'
or 'stretching'
New Events:
- Enter 'enter'
- Leave 'leave'
- Pointer Enter 'pointerenter'
- Pointer Leave 'pointerleave'
- Pointer Drag Start 'pointerdragstart'
- Pointer Drag End 'pointerdragend'
- Pointer Drag Move 'pointerdragmove'
- Pointer Drag Enter 'pointerdragenter'
- Pointer Drag Leave 'pointerdragleave'
New Classes:
- PointerDragEvent extends PointerEvent
- GlobalCoordinates (contains Vectors for world, page, screen)
New ICapturePointerConfig Property:
- captureDragEvents (whether to emit drag events to the actor)
Additional:
- PointerEvent now contains original pointer object.
- Deprecated some coordinate properties in favour of …

[#134] Add drag and drop support off of actors

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Traits/OffscreenCulling.ts
src/spec/EngineSpec.ts

Closes #949
- Correct bounds check to check `drawWidth/drawHeight` in a hidpi scenario
- `suppressHiDPIScaling` now also suppresses pixel ratio based scaling

[#949] Fix offscreen culling in hidpi mode

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Actor.ts
src/engine/Drawing/Animation.ts
src/engine/Drawing/Polygon.ts
src/engine/Drawing/Sprite.ts
src/engine/Drawing/SpriteSheet.ts
src/engine/Interfaces/IDrawable.ts
src/engine/Resources/Texture.ts
src/engine/Util/CullingBox.ts
src/spec/ActorSpec.ts

Corrects the sprite regression seen in the v0.16.0 regression tests. Essentially sprite height and width where overloaded and meant both natural and scaled size at different points in time. This PR extracts and separates width/height from drawWidth/drawHeight
- Rename `naturalWidth` & `naturalHeight` to `width` & `height`
- Add a `drawWidth` & `drawHeight` concept matching `Engine`

Prevent sprite drawing context from being corrupted

---

CHANGELOG.md

Update change log for 0.16.0 release

[chore] Update CHANGELOG.md

---

CHANGELOG.md
src/engine/Resources/Sound.ts

Closes #953
Tested audio locally, observed no warning
- Switch to `setValueAtTime` instead of `value` see https://webaudio.github.io/web-audio-api/#dom-audioparam-setvalueattime
- Update changelog

[#953] Fix issue to comply with audio deprecation warning

---

CHANGELOG.md
src/engine/Engine.ts

Currently Chrome and possibly other browsers can incorrectly report the scaling as less than a pixel, which never makes sense. This seems to happen if you have monitors that are HiDPI and non-HiDPI connected at the same time. This change forces scaling to be at least 1 to prevent odd visual artifacts.
- Force the minimum dpi scale to be at least 1

[bugfix] Prevent negative scaling in hidpi/non-hidpi hybrid scenarios

---

CHANGELOG.md
sandbox/tests/physics/physics.ts
src/engine/Actor.ts
src/engine/Collision/Body.ts
src/engine/Collision/BoundingBox.ts
src/spec/ActorSpec.ts

Closes #948
- Added `isGeometryDirty` check
- Watch both height/width and scale for changes and trip recalculates

[#948] Detect when CollisionArea geometry must be recalculated

---

CHANGELOG.md
src/engine/Timer.ts
src/spec/TimerSpec.ts

Closes #905.  
- Allow timers to repeat execution a finite number of times via `new ex.Timer(fn, interval, numTimes);`
- Allow times to be reset with a different limit via `timer.reset(interval, numTimes)`
- Allow access to the number of times a timer has been executed via timer.timesRepeated

Add finite execution count limit to timers

---

docs/source/quickstart.rst

If you're following along with the quickstart guide, after the step
where you add the ball, it says the ball will bounce off of the paddle
but it doesn't until you've added the precollision handler later on
in the tutorial.
This change adds the precollision handler when adding the ball, then
updates it later for breaking the bricks.

[chore] [docs] Fix breakout ball collision step

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Engine.ts
src/engine/Index.ts
src/spec/ActorSpec.ts

Closes #705 
- Add `EngineDefaultOptions` Singleton to provide access for Engine's default options
- Add basic support of Global and Local scopes for `Actor.anchor`.

[#705] Allow setting a global anchor default for Actors

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Scene.ts
src/spec/ActorSpec.ts
src/spec/SceneSpec.ts

Closes #981 
- Actor sets _isKilled to true before calling scene remove
- Scene.Remove calls entity.kill() if it isn't already dead (i.e. it was triggered through a process other than actor.kill()
- Scene.Remove this._broadphase.untrack(entity.body) is redudant to this._removeChild(entity) which also calls this method
Have not created/run unit tests.  This is forthcoming.

[#981] Fix scene remove should kill actor

---

GruntFile.js

===PR Checklist===
Closes #
- Remove object spread operator since excaliburjs/excaliburjs.github.io still is on Node 6 👎

[chore] Fix Gruntfile to be compatible with Node 6.x

---

CHANGELOG.md
src/engine/Actor.ts

Closes #978
- No behavioral changes, just surfaces type info for events that currently need to be handled more "manually". Let me know if this still needs a CHANGELOG entry.

[#978] Add type info for exit/enter viewport events to actors

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

It looks like GitHub has added [UI-based support](https://blog.github.com/2018-05-02-issue-template-improvements/) for multiple issues templates (previously only available  via [query strings](https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/)).

Split issue templates into separate files

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/kill/kill.html
sandbox/tests/kill/kill.ts
src/engine/Collision/DynamicTreeCollisionBroadphase.ts
src/engine/Collision/Pair.ts
src/engine/Scene.ts
src/spec/CollisionSpec.ts
src/spec/SceneSpec.ts

Closes #975
- Checks both sides of the collision
- Handles edge case with kill
- Adds tests

[#975] Fix collision pair generation to ensure ordering doesnt matter

---

docs/source/features.rst

Closes #1036 
- Adds missing back-tick to features doc bullet point about rigid body physics

[#1036] Fix typo in features.rst in rigid body bullet point

---

CHANGELOG.md
src/engine/Events.ts

Closes #1066
- Added EvenTypes enum to Events.ts
First time PR Questions:
- Not sure how to test this - if there is a place where I can drop in the enum values to make sure it's encluded do let me know.
- Additionally - I noticed that there two events mapping to the same string value - `EventType.Enter` as well as `EventType.EnterTrigger` - what's the reason for this?
- Do I need to open an issue for this?
- Do I update the changelog?
Tested locally - with this simple scenario and seems good.

[#1066] Add EventTypes enum to Events

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Algebra.ts
src/engine/Collision/Body.ts
src/engine/Collision/BoundingBox.ts
src/engine/Collision/CircleArea.ts
src/engine/Collision/EdgeArea.ts
src/engine/Collision/PolygonArea.ts
src/engine/Drawing/Color.ts
src/engine/Drawing/SpriteSheet.ts
src/engine/Label.ts
src/engine/Particles.ts
src/engine/TileMap.ts
src/engine/Trigger.ts
src/engine/Util/DrawUtil.ts

Closes #1085
- Changed ex.Color constants to be static getters
- Changed ex.Vector constnats to be static getters
- Updated main source to avoid any unnecessary `.clone()`'s
- Update changelog

[#1085]  Update ex.Color and ex.Vector constants

---

src/engine/Camera.ts
src/spec/SceneSpec.ts

Closes #1078 
- Correct left side viewport calculation
- Add tests for all sides of culling

[#1078] Fix issue with offscreen culling on left side of screen

---

CHANGELOG.md
src/engine/Camera.ts
src/engine/Loader.ts

Closes #1120
Fixed wrong `Camera` and `Loader` scaling on HiDPI screens when engine option `suppressHiDPIScaling` is set.

Fixed wrong scaling on HiDPI screens when engine option suppressHiDPIScaling is set

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Polyfill.ts
src/engine/index.ts

Closes #1132 
The polyfill import was a side-effect based import, meaning webpack could not reasonably know that it needed to preserve a certain order. 
Fix confirmed in browserstack latest safari
@excaliburjs/core-contributors Should we consider a hotfix for this?
- Fix p1 bug where minified excalibur polyfills were not being applied correctly

[#1132] Guarantee polyfill application

---

CHANGELOG.md
src/engine/Drawing/Animation.ts
src/spec/AnimationSpec.ts

Closes https://github.com/excaliburjs/Excalibur/issues/1172
- Updates Animation to remove the conditional around passing `flipHorizontal/Vertical` to its current Sprite instance, as these should _always_ be passed to ensure their "flipped" state is accurate.
- Added tests to ensure that the flag can be flipped in _both_ directions now, as previously it could only be set to `true`

#1172 Fix animation flipping behavior

---

package-lock.json
src/spec/SpriteSheetSpec.ts

Closes #1199
It was possible for the wrong sprite sheet to be loaded during the test depending on test execution order
- Explicitly load the sprite sheet texture for each test

[#1199] Fix flakey test, possible for wrong sprite sheet to be loaded

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/input/iframe.html
sandbox/tests/input/iframe.ts
sandbox/tests/input/innerframe.html
src/engine/Input/Keyboard.ts

Closes #1294
- Listen to `window.top` if available to grab the topmost window

[#1294] Fix excalibur key events in iframe

---

version.js

Closes #1309
- When building on CI, the build scripts no longer require `GH_TOKEN` to be set if the fork being built is anything other than excaliburjs/Excalibur.
- If GH_TOKEN is not set then the version number for the build is set to fork-abc/Excalibur, where abc/Excalibur is the name of the forked repository.

Travis: Don't require GH_TOKEN when building a fork

---

src/engine/Resources/Sound/AudioInstance.ts
src/spec/WebAudioInstanceSpec.ts

Closes #1317
- Only apply volume ramp if sound is already playing.

[#1317] Don't ramp volume when set at start of playback

---

src/engine/Actions/ActionContext.ts
src/engine/Actor.ts
src/engine/Camera.ts
src/engine/Collision/Collider.ts
src/engine/Collision/Shape.ts
src/engine/Debug.ts
src/engine/Docs/Actions.md
src/engine/Docs/BoxAndPolygonShape.md
src/engine/Docs/Cameras.md
src/engine/Docs/CircleShape.md
src/engine/Docs/EdgeShape.md
src/engine/Docs/Engine.md
src/engine/Docs/Index.md
src/engine/Docs/Loadables.md
src/engine/Docs/Resources.md
src/engine/Docs/SpriteEffects.md
src/engine/Drawing/Animation.ts
src/engine/Drawing/Sprite.ts
src/engine/Engine.ts
src/engine/Loader.ts
src/engine/Resources/Gif.ts
src/engine/Resources/Sound/Sound.ts
src/engine/Resources/Texture.ts
src/engine/Util/Log.ts

Fixes broken TypeDoc type references

[bugfix] Fix doc type references

---

CHANGELOG.md
src/engine/Input/Pointer.ts

Closes #1345
- Add's strong type signatures to the `Pointer` type for `on(...)`, `once(...)`, and `off(..)` handlers

[#1345] Fix typing on pointer event handlers

---

CHANGELOG.md
src/engine/TileMap.ts
src/spec/TileMapSpec.ts

Closes #1418 
TileMapImpl.collides() got stuck infinitely on the `trace points for overlap` loop when the actor's size is zero.
- Check size of actor before deciding whether to run the collision logic
- Return null when actor width or height is 0

Fix freeze when actor width or height is 0 and tilemap is shown

---

package-lock.json
package.json

- [N/A] ~~:microscope: existing tests still pass~~ 
- [N/A] ~~:see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)~~
- [N/A] ~~:triangular_ruler: new tests written and passing / old tests updated with new scenario(s)~~
Closes #1504
- Reverts typedoc to an older version, link generation changed a few months back will open an issue with typedoc to discuss a path forward

[#1504] Fix typedoc generated links by reverting to older version

---

.storybook/manager.js
CHANGELOG.md
src/engine/Input/Keyboard.ts
src/stories/Actions.stories.ts
src/stories/Anchors.stories.ts
src/stories/Keyboard.stories.ts
src/stories/Pointers.stories.ts
src/stories/utils.ts

Closes #1510
- Fix `Keyboard.init` throwing error when embedded in cross-origin iframe
- Add Keyboard story
- Fix Anchors stories so they show up again
- Fix Pointer stories and use `PointerScope.Canvas` in Storybook
- Disable Storybook shortcuts so they don't conflict with keyboard-enabled stories
Example of it working in iframe:

fix(Keyboard): Fix accessing cross-origin frame exception

---

CHANGELOG.md
src/engine/Scene.ts
src/spec/SceneSpec.ts

Closes #1553
- Update the Scene `onInitialize` order
- Add test to confirm order works

fix: [#1553] Scene `onInitialize` order

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Docs/Engine.md
src/engine/Docs/Screens.md
src/engine/Engine.ts
src/engine/Screen.ts
src/engine/index.ts
src/spec/EngineSpec.ts
src/spec/ScreenSpec.ts
version.js

Closes #1617 
- Refactors and creates a screen abstraction for managing all things resolution & viewport related logic
- Adds and fixes tests for the screen abstraction

feat: Screen Resolution Abstraction

---

CHANGELOG.md
src/engine/Actor.ts
src/spec/ActorSpec.ts

Fixes additional issue with #1636 the problem is that if an animation switches inside of an action or another process in the main before animations have a time to be processed the same flicker will happen again.
- Calls an empty tick when switching to a new animation to ensure animation is ready
- Adds tests

fix: [#1636 ] First frame flicker when switching to an animation

---

CHANGELOG.md
src/engine/Actions/Action.ts
src/spec/ActionSpec.ts

Closes #1638 
- Calculate the equivalent velocity needed to lerp instead of directly setting position
- Added tests

fix: [#1638] Re-tool easeTo actions to use velocity

---

CHANGELOG.md
src/engine/Drawing/Color.ts
src/spec/ColorSpec.ts
src/stories/ParticleEmitter.stories.ts
src/stories/utils.ts

HI, As mentioned on the Issue #1536 (https://github.com/excaliburjs/Excalibur/issues/1536) I ported the [Particle Tester}(https://github.com/excaliburjs/particle-tester) into Storybook of the main repo.
Basically it's the same using the Knobs provided by the addon. The only problem that I haved it's to support the Color Selecto to be more Flexible on the options that we show, I included a new static function fromRGBString to create a Color from a rgb or rgba string used by the color knob.
If you want, I can change this and back to a Static list of colors or move this functionality outside of the Color class.
- Added the ParticleEmitter Story on Storybook
- Added a function to create and parse the RGB and RGBA from string on Color class. (This is for use directly the Knob color provided by …

docs: Added ParticleEmitter Story on Storybook

---

CHANGELOG.md
src/engine/Scene.ts

Hello,
This minor change should address #1363.
As additional information, I noticed there aren't any usages within the codebase which invoke the parameter-less constructor for `Scene`. However, there are usages with the `Engine` argument supplied scattered throughout spec and test files. The usages of `new Scene()` appear to be confined to the documentation.
I also noticed there had been a change made in the past (#1068) which caused the `Engine` argument to be mandatory in the constructor signature to begin with. It's not clear to me exactly why that was done given the context available.
---

fix: Make engine parameter optional for scene constructor

---

src/engine/Docs/Labels.md
src/engine/Label.ts

Hello,
I took a look at #1364 and I'd suggest the least destructive approach is to amend the documented usage for that particular constructor overload for `Label`.
Before arriving at this conclusion, I toyed with the idea of accepting a valid value to the CSS `font` shorthand property. However, trying to get a simple regular expression to parse all cases seemed a bit overkill for what it's worth (e.g. `oblique 10deg small "Comic Sans"` is technically a valid value). The fact `Label` fragments the various font properties up into separate properties (i.e. `fontSize`, `fontStyle`, etc.) is the complication that makes parsing necessary I think.
I also noticed `LabelSpec.ts` has been suppressed entirely. I enabled it and ran the tests out of curiosity, noticed a failing one, and didn't go any …

docs: Update documented usage for label constructor

---

CHANGELOG.md
src/engine/Docs/Constructors.md
src/engine/Docs/Index.md
src/engine/ScreenElement.ts

Hi, I removed the UIActor Class in favor to move the implementation to the ScreenElement (https://excaliburjs.com/docs/api/edge/classes/_screenelement_.screenelement.html).
I update the documentation and added the inform of this breaking change on the Changelog.md
Closes #1656
- Fix #1656

chore: [#1656] Remove UIActor Stub

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Collision/ConvexPolygon.ts
src/spec/CollisionShapeSpec.ts

Fix CollisionShapeSpec Draw to render relative position from the base of the position arg, because the Actor drawing its translating the canvas context.
```typescript
const actor = new Actor(0, 0, 50, 50, Color.Red);
//actor.anchor.setTo(0, 0);
game.add(actor);
```
```typescript
const actor = new Actor(0, 0, 50, 50, Color.Red);
actor.anchor.setTo(0, 0);
game.add(actor);
```
```typescript
const actor = new Actor(0, 0, 50, 50, Color.Red);
actor.anchor.setTo(0.75, 0.75);
game.add(actor);
```
Closes #1535

fix: [#1535] Actor without a drawing doesn't set anchor properly

---

CHANGELOG.md
src/engine/Screen.ts
src/spec/ScreenSpec.ts

Closes #1676
- Falls back to "crisp-edges" if "pixelated" doesn't work see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)
- Adds tests for these property changes

fix: [#1676] Fallback support for Firefox when anti-aliasing turned off

---

CHANGELOG.md
sandbox/html/index.html
sandbox/src/game.ts
src/engine/Algebra.ts
src/engine/Input/Pointers.ts
src/engine/Screen.ts
src/engine/TileMap.ts
src/spec/ScreenSpec.ts

Closes #1733
Closes #1734
- Breaking change: `DisplayMode.FullScreen` will now scale the game to fit the available space, preserving the `aspectRatio`. This matches the browser "FullScreen" api behavior
- New: `DisplayMode.Dynamic` now does what `DisplayMode.FullScreen` used to do, the resolution and viewport dynamically adjust to fit the available space, DOES NOT preserve `aspectRatio`
- Fix: In the the browser "FullScreen" api, coordinates are now correctly mapped from page space to world space
- Added: Screen helpers for mapping between world, screen, and page space coordinates
- Deprecate: `DisplayMode.Position` CSS can accomplish this task better than Excalibur
- Tests!

feat: [#1733][#1734] New FullScreen and Dynamic DisplayModes

---

src/engine/Label.ts

Fixes issue where Label collider was also being drawn in the case of a non-zero width and height :(

fix: Labels should support non-zero width/height

---

src/engine/Screen.ts
src/spec/ScreenSpec.ts

Fix fullscreen api coordinate mapping, the coordinate mapping was not working in Fixed mode (it looked like it was working but only because it was running in Fit display mode)

fix: Fullscreen API coordinate mapping

---

CHANGELOG.md
src/engine/Loader.ts
src/spec/LoaderSpec.ts

Fixes issue where loader dom elements leak and pile up in the DOM if restarting the game

fix: Loader DOM element leak, press enter to start

---

CHANGELOG.md
src/engine/Input/Keyboard.ts
src/spec/KeyInputSpec.ts

Closes #
Allows getting at the typed character (or "key") from the keyboard event, as well as the originally handled event for advanced scenarios.
- Add `value` which is the [`key` value](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) from the original event
- Add `originalEvent` to allow accessing the original `KeyboardEvent`

feat(KeyEvent): add key value and expose raw event

---

CHANGELOG.md
package.json
sandbox/src/game.ts
sandbox/tests/camera/zoom.ts
sandbox/tests/culling/culling2.ts
sandbox/tests/physics/fastphysics.ts
sandbox/tests/physics/physics2.ts
sandbox/tests/tilemap/tilemap.ts
sandbox/tests/zoom/zoom.ts
src/engine/Actor.ts
src/engine/Camera.ts
src/engine/EntityComponentSystem/Entity.ts
src/engine/EntityComponentSystem/Query.ts
src/engine/EntityComponentSystem/QueryManager.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Screen.ts
src/engine/Traits/OffscreenCulling.ts
src/spec/CameraSpec.ts
src/spec/EngineSpec.ts
src/spec/GraphicsSystemSpec.ts
src/spec/QueryManagerSpec.ts
src/spec/ScreenSpec.ts
src/stories/Actions.stories.ts

Offscreen culling events were not firing in the new graphics system, this updates entities with an "offscreen" tag if they are offscreen
- "offscreen" tag
- enter and exit viewport events fire once more for the new graphics system
- Bug in ECS component removal :boom: where entities were being removed from queries they still qualified for

fix: Offscreen Culling Events in new graphics system

---

CHANGELOG.md
sandbox/src/game.ts
sandbox/tests/coordinates/coordinates.ts
sandbox/tests/debug/boundingbox.ts
sandbox/tests/input/pointer.ts
src/engine/Actor.ts
src/engine/Drawing/CanvasDrawingSystem.ts
src/engine/EntityComponentSystem/Entity.ts
src/engine/EntityComponentSystem/EntityManager.ts
src/engine/EntityComponentSystem/Query.ts
src/engine/EntityComponentSystem/System.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Label.ts
src/engine/Particles.ts
src/engine/TileMap.ts
src/spec/ActorSpec.ts
src/spec/EntitySpec.ts
src/spec/GraphicsSystemSpec.ts
src/spec/QueryManagerSpec.ts
src/spec/QuerySpec.ts
src/spec/TransformComponentSpec.ts

This PR simplifies `Entity` to make only one way to add/remove components. 
- Removes the `components` object on Entity as a way of adding/removing components
- Extracts initializing entities with a template entity into a separate method, supports templates with children
- Support cloning entities with children
- Rename's `add()` to `addChild()`, `remove()` to `removeChild()`, and `removeAll()` to `removeAllChildren()`

chore: Refactor Entity

---

CHANGELOG.md
src/engine/Polyfill.ts
src/engine/Resources/Sound/AudioContext.ts

Closes #1848
`webkitAudioContext.decodeAudioData` does not support the newer Promise-style API offered by the standard and instead uses the older callback-based method:
https://stackoverflow.com/a/52536753
This PR adds a polyfill that emulates the Promise-style API in webkit browsers.

fix: [#1848] Add polyfill for decodeAudioData on Safari

---

CHANGELOG.md
karma.conf.js
src/engine/Graphics/Raster.ts
src/spec/GraphicsRasterSpec.ts

Closes #1897
- Fixes issue where Raster bitmap grows every time it is rasterized using padding

fix: [#1897] Prevent backing bitmap from growing with padding

---

CHANGELOG.md
sandbox/tests/graphics/index.html
sandbox/tests/graphics/index.ts
sandbox/tests/pointer/index.html
sandbox/tests/pointer/pointer.ts
src/engine/Actor.ts
src/engine/Input/Pointer.ts
src/engine/Input/PointerEvents.ts
src/engine/Input/Pointers.ts
src/spec/ActorSpec.ts
src/spec/PointerInputSpec.ts

Closes #1922
- Sorts actors for pointer events in high->low z order (ties broken by ids)

fix: [#1922] Propagate pointer events in high->low z order

---

CHANGELOG.md
src/engine/Input/Pointers.ts
src/spec/PointerInputSpec.ts

Closes #1439
- Emit event at engine pointers level

fix: #1439 engine level pointer events

---

CHANGELOG.md
src/engine/Scene.ts
src/engine/Timer.ts
src/spec/CollisionSpec.ts
src/spec/SceneSpec.ts
src/spec/TimerSpec.ts

Closes #1864
Closes #1865
- Adds `Timer.start()` to explicitly start timers, they will no longer implicitly start when added to a scene.
- Adds `Timer.stop()` to stop and "rewind" a timer
- Adds `Timer.timeToNextAction` will return the milliseconds until the next action callback
- Adds `Timer.timeElapsedTowardNextAction` will return the milliseconds counted towards the next action callback
- Renames the `Timer.unpause()` to `Timer.resume()`

fix: [#1864] [#1865] Timer.start() must be called + rename Timer.unpause() -> Timer.resume()

---

CHANGELOG.md
src/engine/Graphics/Sprite.ts
src/spec/GraphicsSpriteSpec.ts

Closes #1863
- Support `GraphicsOptions` width and height
- Tests

fix: [#1863] Support width/height args for Sprites

---

CHANGELOG.md
src/engine/Graphics/ImageSource.ts
src/spec/GraphicsImageSourceSpec.ts

Closes #1855
- Add warning log for svg and gif
- Test

feat: [#1855] Add warning to ImageSource for partially supported images

---

CHANGELOG.md
src/engine/Actions/ActionContext.ts
src/spec/ActionSpec.ts

Closes #1860
- Add overload to `moveTo()`, `moveBy()`, `easeTo()`, `scaleTo()`, and `scaleBy()` now have vector args
- Tests

feat: [#1860] Add vector overload to actions that take an x,y

---

CHANGELOG.md
src/engine/Screen.ts
src/spec/ScreenSpec.ts

There's something I noticed while writing tests and don't know if I'm missing something or not. The properties `drawWidth` and `drawHeight` use `scaledWidth` and `scaleHeight` internally, and then multiply that by `pixelRatio`. The thing is that `scaledWidth` and `scaleHeight` are defined by `resolution.width/pixelRatio` and `resolution.height/pixelRatio` respectively. Therefore, wouldn't this cause `pixelRatio` to be ignored? Or am I not addressing something? 
Closes #2045
- Added new property to class `Screen` that encapsulates screen center coordinates calculations.

Adding property to get screen center

---

src/engine/Graphics/ImageSource.ts
src/engine/Resources/Resource.ts
src/spec/GraphicsImageSourceSpec.ts

Closes #2049
- Improve ImageSource error with specific information
- Wrap the previous error [object](https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Resources/Resource.ts#L68), with a generic `Error` to enhance error handling
- Provide a syntax more lightweight when dealing with [error propagation](https://github.com/excaliburjs/Excalibur/blob/main/src/engine/Graphics/ImageSource.ts#L86)
- Add new test case

fix #2049: ImageSource loading error message

---

sandbox/tests/fitscreen/fitscreen.ts
sandbox/tests/fitscreen/index.html
sandbox/tests/gif/animatedGif.ts
src/engine/Camera.ts
src/engine/Engine.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
src/engine/Screen.ts
src/spec/CameraSpec.ts
src/spec/ScreenSpec.ts

TODO:
Closes #2076
- Deferred initialization of scene/camera until final resolution is calculated

fix: [#2076] Defer initialization until after final resolution calculated

---

CHANGELOG.md
src/engine/Class.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/ColliderComponent.ts
src/engine/Collision/Colliders/Collider.ts
src/engine/EventDispatcher.ts
src/engine/Graphics/Animation.ts
src/engine/Input/PointerAbstraction.ts
src/engine/Resources/Resource.ts
src/engine/Trigger.ts
src/spec/CollisionSpec.ts
src/spec/EventSpec.ts

Closes #2047
- `EventDispatcher` - doesn't require the target object. The context of `this` is not tampered anymore.
- `PointerAbstraction` - is fixed to maintain reference
- The following Engine's pieces: `Collision` `Graphics` `Resources` `Trigger` are updated to accomodate the new EventDispatcher behavior.

Refactor: Remove .call() in EventDispatcher

---

CHANGELOG.md
src/engine/Collision/Solver/ArcadeSolver.ts
src/spec/ArcadeSolverSpec.ts

Fixes an issue where overlapping tiles would cause a jitter, due to the arcade solver double solving the same mtv
- Check if contact overlaps before solving position
Before 
After

fix: Arcade Solver Jitter on stacked/overlapped tiles

---

README.md

We no longer use TravisCI for our continuous integration builds.

docs: Remove TravisCI badge

---

.github/workflows/browsersupport.yml
.github/workflows/build.yml
.github/workflows/deploy.yml

Splits single build step into:
- core build (faster)
- storybook examples
- API docs (typedoc)
- Use `cache: npm` built in to setup-node action
- Add new jobs
- Set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true` for the other jobs
- Use `--ignore-scripts` for other jobs (5-8s speedup)
- Use new `node-version-file: '.nvmrc'` support 🎉

chore(ci): optimize build jobs

---

.github/CONTRIBUTING.md

Fixes the semantic heading levels of the Contributing Guide.

docs: Fix semantic headings

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Util/Clock.ts
src/spec/ClockSpec.ts

This PR fixes an unreleased issue where sometimes when constraining fps with the clock, the update loop would get out of phase and the `elapsed` time passed to the mainloop could be nearly double the fps. Ironically the clock loops were running correctly, the elapsed time passed to the simulation was wrong.
- Refactored the update to be a little easier to read
- Shifts the update elapsed time to be in-phase with the fps, the loop still counts updates correctly to match fps

fix: Clock runs game simulation too fast sometimes when limiting fps

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Graphics/SpriteFont.ts
src/spec/GraphicsTextSpec.ts

This PR changes SpriteFonts to log once per detected issue.
- Update SpriteFont warning tests

fix: Prevent SpriteFonts from logging excessive warnings

---

CHANGELOG.md
sandbox/src/game.ts
sandbox/tests/gif/animatedGif.ts
src/engine/Engine.ts
src/engine/Graphics/Circle.ts
src/engine/Graphics/Context/texture-loader.ts
src/engine/Graphics/Filtering.ts
src/engine/Graphics/Font.ts
src/engine/Graphics/Graphic.ts
src/engine/Graphics/ImageSource.ts
src/engine/Graphics/Polygon.ts
src/engine/Graphics/Raster.ts
src/engine/Graphics/Text.ts
src/engine/Graphics/index.ts
src/engine/Label.ts
src/engine/Loader.ts
src/spec/EngineSpec.ts
src/spec/GraphicsCircleSpec.ts
src/spec/GraphicsImageSourceSpec.ts
src/spec/GraphicsPolygonSpec.ts
src/spec/GraphicsTextSpec.ts

Related to the roadmap for v0.26.0 #1161, this PR exposes different webgl texture blending modes to the user. I've attempted to give them names that are indicative of their function.
* `ex.ImageFiltering.Blended` -  Blended is useful when you have high resolution artwork and would like it blended and smoothed
* `ex.ImageFiltering.Pixel` - Pixel is useful when you do not want smoothing aka antialiasing applied to your graphics.
After the v0.25.0 and the switch to webgl, Excalibur really only catered to pixel art styles, now supports hi-res art styles as well!
- Excalibur will set a "default" blend mode based on the `ex.EngineOption` antialiasing property, but can be overridden per graphic
- `antialiasing: true`, then the blend …

feat: Support image filtering modes on ImageSource & Raster Graphics

---

src/engine/Actions/Action/RotateBy.ts
src/engine/Actions/Action/RotateTo.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/Solver/RealisticSolver.ts
src/engine/Debug/DebugSystem.ts
src/engine/Drawing/Animation.ts
src/engine/Drawing/Sprite.ts
src/engine/Graphics/Animation.ts
src/engine/Loader.ts
src/engine/Math/matrix.ts
src/engine/Math/util.ts
src/engine/Particles.ts
src/engine/Resources/Gif.ts
src/engine/Resources/Sound/WebAudioInstance.ts
src/engine/Util/Util.ts
src/engine/index.ts
src/spec/ActionSpec.ts
src/spec/ActorSpec.ts
src/spec/MathSpec.ts
src/spec/UtilSpec.ts

The PR consolidates the math utils out of the cursed old Util folder/file and import site.
It also promotes the useful math utility functions to hang off the UMD global 🎉

refactor: Move math utils, deprecate old import site

---

CHANGELOG.md
src/engine/Actor.ts
src/spec/ActorSpec.ts

Closes #2192
- Adds a new property `Actor.localCenter` to retrieve the center in local coordinates
- Updates the `Actor.center` property to use the global position from the `TransformComponent`

fix: [#2192] Actor.center returns global position

---

CHANGELOG.md
src/engine/Input/PointerEventReceiver.ts

Closes #2224
Touch action must be set on the event listener target

fix: [#2224] Disable touch action on pointer target for mobile platforms

---

CHANGELOG.md
src/engine/Graphics/Context/image-renderer/image-renderer.ts

Fixes an issue in Pixel 6 when using MAX_TEXTURE_IMAGE_UNITS, in the interest of supporting the device we're artificially capping the max textures to 125

fix: Pixel 6 devices crash when MAX_TEXTURE_IMAGE_UNITS used

---

CHANGELOG.md
src/engine/Collision/Colliders/CollisionJumpTable.ts
src/spec/CollisionShapeSpec.ts

This PR corrects collisions when offset, the reason this was a problem was there were inaccurate collision normal

fix: polygon colliders have inaccurate collision normals when offset

---

.github/workflows/deploy.yml
package-lock.json
package.json
scripts/excalibur-version.js
scripts/release.js
version.js
webpack.config.js

Preparing for v0.25.3, updating release automation to improve quality of life

chore: Update release automation

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/triangulation/index.html
sandbox/tests/triangulation/index.ts
src/engine/Collision/ColliderComponent.ts
src/engine/Collision/Colliders/PolygonCollider.ts
src/engine/Collision/Colliders/Shape.ts
src/spec/CollisionShapeSpec.ts

This PR adds arbitrary non-convex polygon support using the `ex.PolygonCollider(...).triangulate()` method which produces a new `ex.CompositeCollider` composed of triangles.
This PR also adds a `tessellate()` which will produce a triangle fan `ex.CompositeCollider`

feat: Add arbitrary non-convex polygon support

---

CHANGELOG.md
src/engine/Collision/BoundingBox.ts
src/engine/Math/vector.ts
src/spec/AlgebraSpec.ts
src/spec/BoundingBoxSpec.ts

Performance improvements, implements a fast `ex.BoundingBox.overlap(...)` and `ex.BoundingBox.transform(...)`

feat: Fast BoundingBox overlap and transform

---

CHANGELOG.md
src/engine/EntityComponentSystem/Components/TransformComponent.ts
src/engine/Input/PointerSystem.ts
src/spec/TransformComponentSpec.ts

This PR adds `zIndexChanged$` to the `ex.TransformComponent` in order to know when the z index changes. This allows the `ex.PointerSystem` to maintain a sorted list which is much faster than using the ECS Query.

perf: Add `zIndexChanged$` + Improve pointer system perf

---

CHANGELOG.md
sandbox/tests/input/keyboard.ts
src/engine/Engine.ts
src/engine/Input/Keyboard.ts
src/spec/EngineSpec.ts

Closes #2263 
This PR adjusts the keyboard & gamepad input updates to the actual end of the frame after the `onPostUpdate` lifecycle. Additionally this adds a number of missing key codes in the `ex.Input.Keys` enum.

fix: #2263 keyboard `wasPressed` works in `onPostUpdate` lifecycle

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Engine.ts
src/engine/Graphics/Font.ts
src/engine/Screen.ts
src/spec/EngineSpec.ts
src/spec/ScreenSpec.ts

Closes #2291
This PR assists in pixelated Text rendering by increasing the number of internal pixels available on the canvas, to do this I added a `pixelRatio` that can be set at `Engine` constructor time.
Before antialiasing is off (pixel art mode), default `pixelRatio`
After antialiasing is off (pixel art mode) but `pixelRatio` is set to 4
- Added `pixelRatio` option to `Engine` constructor
- Added/updated tests
- Commented Font renderer

feat: Add pixelRatio override for Text rendering

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Graphics/SpriteSheet.ts
src/spec/SpriteSheetSpec.ts

Closes #2288
Adds a new builder for producing sprite sheets with custom slices of source view for non-uniform SpriteSheets

feat(graphics): [#2288] Implement SpriteSheet builder with custom sourceViews

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Collision/Colliders/Collider.ts
src/engine/Collision/Colliders/CompositeCollider.ts
src/engine/Collision/CollisionSystem.ts
src/engine/Collision/Detection/CollisionContact.ts
src/spec/CompositeColliderSpec.ts

Closes #2300 
This PR solves the issue of duplicate `collisionstart`/`collisionend` events by keeping track of the `CompositeCollider` in the contact id (which makes it no longer unique) but allows the dispatch logic for start/end to work unchanged in the `CollisionSystem`. This is done with a slightly gross hack to decorate colliders with a composite id if they are part of a composite collider.

fix: [#2300] CompositeColliders count as a whole for collisionstart/collisionend events

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Engine.ts
src/engine/Flags.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Input/PointerEventReceiver.ts
src/engine/Input/PointerSystem.ts
src/engine/Screen.ts
src/engine/Util/Toaster.css
src/engine/Util/Toaster.ts
src/engine/index.ts
src/spec/EngineSpec.ts
src/spec/ToasterSpec.ts

See discussion #2304 
This PR adds the 2D canvas rendering context as a fallback if webgl fails for any reason. Also returns the ability to flag on the 2D canvas context as well.

feat(graphics): Add canvas 2d fallback mechanism

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Screen.ts
src/spec/ScreenSpec.ts

Related #2272
This PR implements a fit screen/container and zoom to avoid the letter boxing, this is achieved by over scaling the viewport and positioning. One caveat is this will clip some drawable area so should only be used in games that are okay with losing some draw space. This PR also adds a `ex.Screen.contentArea` which will return the "safe space" to place content given the current screen size.
New display modes `ex.DisplayMode.FitScreenAndZoom` and `ex.DisplayMode.FitContainerAndZoom`
Notice that some of the viewport is offscreen

feat: [#2272] Add Fit Screen/Container and Zoom

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Screen.ts
src/spec/ScreenSpec.ts

Closes #2324 
This PR adds an additional optional argument to `ex.Screen.goFullScreen('some-element-id')` to target a specific element for the browser fullscreen API.
Example:
```html
<button id="fullscreen">Go Fullscreen</button>
<div id="container" class="container">
<div class="ui" style="position: absolute; right: 0">
<div>Some text</div>
<button>Click me!</button>
</div>
<canvas id="game"></canvas>
</div>
```
```typescript
const game = new ex.Engine({
...
canvasElementId: 'game'
});
var fullscreenButton = document.getElementById('fullscreen') as HTMLButtonElement;
fullscreenButton.addEventListener('click', () => {
if (game.screen.isFullScreen) {
game.screen.exitFullScreen();
} else {
game.screen.goFullScreen('container'); …
```

feat: [#2324] Add FullScreen Target Element Id

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/parallel/index.html
sandbox/tests/parallel/index.ts
src/engine/Actions/Action/ActionSequence.ts
src/engine/Actions/Action/Blink.ts
src/engine/Actions/Action/Delay.ts
src/engine/Actions/Action/EaseBy.ts
src/engine/Actions/Action/Fade.ts
src/engine/Actions/Action/Follow.ts
src/engine/Actions/Action/Meet.ts
src/engine/Actions/Action/MoveBy.ts
src/engine/Actions/Action/MoveTo.ts
src/engine/Actions/Action/ParallelActions.ts
src/engine/Actions/Action/RotateBy.ts
src/engine/Actions/Action/RotateTo.ts
src/engine/Actions/Action/ScaleBy.ts
src/engine/Actions/Action/ScaleTo.ts
src/engine/Actions/ActionContext.ts
src/engine/Actions/ActionsComponent.ts
src/engine/Actions/Index.ts
src/spec/ActionSpec.ts

Closes #242
This PR implements 2 new `Action` types to enable running parallel actions. `ActionSequence` which allows developers to specify a sequence of actions to run in order, and `ParallelActions` to run multiple actions at the same time.
Example, moves the actor in a box while rotating it at the same time
```typescript
var sequence1 = new ex.ActionSequence(actor, ctx => {
ctx.easeBy(ex.vec(200, 0), 1000, ex.EasingFunctions.EaseInOutCubic);
ctx.delay(500);
ctx.easeBy(ex.vec(0, 200), 1000, ex.EasingFunctions.EaseInOutCubic);
ctx.delay(500);
ctx.easeBy(ex.vec(-200, 0), 1000, ex.EasingFunctions.EaseInOutCubic);
ctx.delay(500);
ctx.easeBy(ex.vec(0, -200), 1000, ex.EasingFunctions.EaseInOutCubic);
ctx.delay(500);
});
var …
```

feat: [#242] Implement Parallel Actions

---

CHANGELOG.md
sandbox/tests/sound/sound.ts
src/engine/Interfaces/Audio.ts
src/engine/Loader.ts
src/engine/Resources/Sound/Sound.ts
src/engine/Resources/Sound/WebAudioInstance.ts
src/engine/Util/StateMachine.ts
src/engine/index.ts
src/spec/SoundSpec.ts
src/spec/StateMachineSpec.ts

This PR adds the ability to `ex.Sound.seek()` to a specific position in the sound, it also adds the `ex.Sound.getTotalPlaybackDuration()` so you may know how long in seconds the sound file is. Lastly `ex.Sound.duration` if set will limit the duration of the clip from where played();
In order to accomplish this, `ex.Sound()` was refactored using a small `ex.StateMachine` implementation
Example
```typescript
const machine = ex.StateMachine.create({
start: 'STOPPED',
states: {
PLAYING: {
onEnter: () => {
console.log("playing");
},
transitions: ['STOPPED', 'PAUSED']
},
STOPPED: {
onEnter: () => {
console.log("stopped");
},
transitions: ['PLAYING']
},
PAUSED: {
onEnter: () => {
console.log("paused")
},
transitions: ['PLAYING', …
```

feat: Add missing Sound features `.seek()`,  `.duration`, & `getTotalPlaybackDuration()`

---

CHANGELOG.md
sandbox/tests/side-collision/index.ts
sandbox/tests/side-collision2/index.ts
src/engine/Collision/BodyComponent.ts
src/engine/Engine.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Scene.ts
src/spec/EngineSpec.ts
src/spec/GraphicsSystemSpec.ts

v0.27.0 Milestone related,
This PR adds the ability to configure a fixed FPS for the update loop. One advantage of setting a fix update is that you will have a more consistent and predictable physics simulation. Excalibur graphics will be interpolated automatically to avoid any jitter in the fixed update.
* If the fixed update FPS is greater than the display FPS, excalibur will run multiple updates in a row (at the configured update elapsed) to catch up, for example there could be X updates and 1 draw each clock step.
* If the fixed update FPS is less than the display FPS, excalibur will skip updates until it meets the desired FPS, for example there could be no update for 1 draw each clock step.
```typescript
const game = new …
```

feat: Implement Fixed timestep

---

CHANGELOG.md
src/engine/EventDispatcher.ts
src/engine/Events.ts
src/spec/EventSpec.ts

Closes #2347
This PR fixes several issues in the `ex.EventDispatcher`
* Concurrent updates of handlers was not handled well, this has been fixed by implementing deferred removal
* If a handler didn't exist the wrong handler would be removed instead (classic splice(-1, 1) bug)

fix: [#2347] EventDispatcher concurrent update issue and removal bug

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/physics/physics.ts
sandbox/tests/side-collision/index.html
sandbox/tests/side-collision2/index.html
sandbox/tests/tilemap-custom-edge-collider/index.html
sandbox/tests/tilemap-custom-edge-collider/index.ts
src/engine/Collision/Colliders/CollisionJumpTable.ts
src/engine/Collision/Colliders/EdgeCollider.ts
src/spec/CollisionShapeSpec.ts

Closes #2353
The PR includes a fix for `EdgeColliders` when placed into a composite collider
TODOs:

fix: [#2353] EdgeColliders in Composite calculate offsets

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/decode-many/index.html
sandbox/tests/decode-many/index.ts
src/engine/Graphics/ImageSource.ts
src/engine/Loader.ts
src/engine/Util/Clock.ts
src/engine/Util/Future.ts
src/engine/Util/Semaphore.ts
src/engine/Util/Util.ts
src/engine/index.ts
src/spec/FutureSpec.ts
src/spec/LoaderSpec.ts
src/spec/SemaphoreSpec.ts

Closes #2359
This PR switches away from `Image.decode()` to use the older method of `Image.onload` this method is more reliable for large or numerous images due to a chromium bug around decode.
@HxShard provided a great codesandbox illustrating the issue https://codesandbox.io/s/happy-gagarin-j1vjr
- Creates a new Future type for working with native Promises' resolve/reject at any time
- Creates a new Semaphore type that can limit async calls in between `enter` and `exit`
- Fixes a small clock schedule bug as well

fix: [#2359] work around image decode limits in chromium

---

CHANGELOG.md
sandbox/tests/physics/physics.ts
src/engine/Actor.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/Colliders/CircleCollider.ts
src/engine/Collision/Solver/ContactConstraintPoint.ts
src/engine/Collision/Solver/RealisticSolver.ts
src/spec/ActorSpec.ts
src/spec/CollisionContactSpec.ts
src/spec/CollisionShapeSpec.ts

Closes #2368
This PR corrects the math around elastic collisions in the realistic collision solver, elastic collisions now preserve energy as expected.
Additionally this PR also fixes an issue with the degrees of freedom limiter

fix: [#2368] elastic collisions & degree of freedom

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Graphics/Sprite.ts
src/spec/SpriteSpec.ts

Related to discussion #2356
- Logs warning if `ex.ImageSource` not yet loaded and a draw was attempted

fix: Add warning if ImageSource not loaded

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Events.ts
src/engine/Interfaces/LifecycleEvents.ts
src/engine/Scene.ts
src/spec/SceneSpec.ts

Closes #1548
- Added optional `data` parameter to `goToScene`, which gets passed to the target scene's `onActivate` method.
```typescript
class SceneA extends ex.Scene {
/* ... */
onActivate(context: ex.SceneActivationContext<{ foo: string }>) {
console.log(context.data.foo); // bar
}
}
engine.goToScene('sceneA', { foo: 'bar' })
```
- Scene `onActivate` and `onDeactivate` methods have been changed to receive a single parameter, an object containing the `previousScene`, `nextScene`, and optional `data` passed in from `goToScene()`

feat: pass data to scene activation from goToScene

---

CHANGELOG.md
sandbox/tests/gotoscene/index.html
sandbox/tests/gotoscene/index.ts
src/engine/Engine.ts
src/spec/EngineSpec.ts

Closes #2379
- Clears out deferred scenes after they've been transitioned

fix: [#2379] Deferred goto preserves wrong scene

---

karma.conf.js
src/spec/ArcadeSolverSpec.ts
src/spec/ClockSpec.ts
src/spec/CollisionSpec.ts
src/spec/ScreenElementSpec.ts
src/spec/SoundSpec.ts
src/spec/SpriteSpec.ts

CI especially in Appveyor fails often, there are few tests have been flaking as well
- Remove standard clock test (the fps limiting is adequately tested via the test clock)
- Speed up some tests
- Fix flakey sprite tests
- Add random seed reporter to help reproduce any future issues

chore: Theoretically address flakey CI

---

src/engine/Engine.ts
src/engine/Scene.ts

Addresses [follow up](https://github.com/excaliburjs/Excalibur/issues/1548#issuecomment-1172504724) in #1548 
- removes the generic in `onActivation` and adds it to the Scene instead. This allows it to be inferred by doing `onActivation(ctx: SceneActivationContext<Data>)` in Scene subclasses.

fix: use generic on Scene for better onActivate data type

---

CHANGELOG.md
src/engine/Engine.ts

Small fix to not require user message and threshold, which was slightly awkward in this situation where you wanted to disable it. Previously you would need to specify `threshold` and `showPlayerMessasge` to disable.
```typescript
configurePerformanceCanvas2DFallback: {
allow: false
}
```

fix: Tweak performance fallback options to be optional

---

CHANGELOG.md
src/engine/Collision/BodyComponent.ts
src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
src/engine/Collision/Solver/ArcadeSolver.ts
src/engine/Collision/Solver/ContactConstraintPoint.ts
src/engine/Collision/Solver/RealisticSolver.ts
src/engine/Graphics/GraphicsSystem.ts
src/spec/BodyComponentSpec.ts
src/spec/GraphicsSystemSpec.ts

This PR fixes an unreleased issue where fixed step update interpolation was incorrect with child actors. The issue was global and local positions were mixed in the interpolate.
- Switch interpolation to use local positions for start and end

fix: Fixed update Interpolation incorrect with child actors

---

CHANGELOG.md
src/engine/Engine.ts
src/spec/EngineSpec.ts

Fixes `engine.on('visible')` not firing by using `document.visibilityState` API to determine current state
Closes #2409
- Fixed `engine.on('visible')` event not firing

fix: [#2409] engine 'visible' event not firing

---

CHANGELOG.md
src/engine/EventDispatcher.ts
src/spec/EventSpec.ts

Closes #2418
- Fixed `EventDispatcher.emit` converting falsy values to `ex.GameEvent`. It will only convert `undefined` or `null` values now.

fix: [#2418] falsey event values being converted to GameEvent

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/EntityComponentSystem/Entity.ts
src/engine/EntityComponentSystem/EntityManager.ts
src/spec/EntitySpec.ts

Closes #2419
- `Actor.scene` is now moved to the base type `Entity.scene` functionality is the same
- Adds scene to entity add/remove processing

fix: [#2419] child entities inherit parent's scene

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/textcrash/index.html
sandbox/tests/textcrash/index.ts
src/engine/Graphics/Font.ts
src/engine/Graphics/FontCache.ts
src/engine/Graphics/FontTextInstance.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Graphics/index.ts
src/spec/TextSpec.ts

Closes #2424
- Implements a global font cache so that any functionally identical fonts can share resources

fix: [#2424] crash when using many ex.Text instances

---

CHANGELOG.md
src/engine/Actor.ts

Closes #2425
- Correct event type

fix: [#2425] incorrect event type in `ex.Actor.on('postupdate')`

---

CHANGELOG.md
sandbox/tests/input/gamepad.ts
src/engine/Input/Gamepad.ts

Closes #2460
- add support for gamepad wasButtonPressed and wasButtonReleased

feat: [#2460] add support for wasButtonPressed and wasButtonReleased

---

CHANGELOG.md
src/engine/Graphics/SpriteSheet.ts
src/spec/SpriteSheetSpec.ts

Closes #2468
- Added `clone()` method to `ex.SpriteSheet`

feat: [#2468] add clone() method to ex.SpriteSheet

---

src/engine/Actions/Action/ScaleTo.ts
src/spec/ActionSpec.ts

Previously if scaling only on the x-axis, the action would never complete.
Closes #2470 
Fixes a bug I found in the `ScaleTo` action, where scaling on the x-axis exclusively may never complete. The `isComplete` method accidentally tested `tx.scale.y` against the x-axis, rather than testing `tx.scale.x` against the x-axis. I wrote the test first, watched it fail, and then fixed the bug and watched the test pass.
It looks like since I'm a first-time contributor I'll need approval from a maintainer to actually run the CI checks, but I pinky swear I ran `npm run all` locally and it all passed. :smile:

Fix x-axis bug in `actions.scaleTo`

---

CHANGELOG.md
sandbox/tests/incorrectside/index.html
sandbox/tests/incorrectside/index.ts
src/engine/Collision/Solver/ArcadeSolver.ts
src/engine/Collision/Solver/RealisticSolver.ts
src/spec/ArcadeSolverSpec.ts
src/spec/RealisticSolverSpec.ts

Closes #2473
This PR fixes an issue where a degenerate 0 sized collision causes issues with the precollision event emit. Previously an erroneous left precollision would be emitted when the minimum translation vector (mtv) was `(-0, -0)`
- Filters out 0 sized contacts in precollision to guard against a degenerate side calculation

fix: [#2473] ignore 0 sized precollisions

---

src/spec/ActorSpec.ts
src/spec/EntitySpec.ts

Fixed in f8d818a39415adc1bcb458635a1c7b0960f4c05d
Closes #2579 
- Adds additional test cases

fix: [#2579] Add tests confirming parent/child scene fix

---

CHANGELOG.md
src/engine/Util/Sound.ts
src/spec/SoundSpec.ts

Closes #2599
- Update regex parsing sound paths to determine audio support

fix: [#2599] Update Sound canPlayFile to handle querystrings

---

CHANGELOG.md
src/engine/ScreenElement.ts
src/spec/ScreenElementSpec.ts

Closes #2597 
- Adds defense to the `ScreenElement` to avoid an unnecessary warning

fix: [#2597] Add defense to ScreenElement ctor for zero width/height

---

CHANGELOG.md
sandbox/tests/input/keyboard.ts
src/engine/Input/Keyboard.ts

This PR adds a fix suggested from SO, where release of the meta key causes the release of all keys
- https://stackoverflow.com/a/73419500/839595
Closes #2608 
Following the repro
* Press A key
* Press Command key
* Release A key
* Release Command key

fix: [#2608] macos meta key issue

---

CHANGELOG.md
src/engine/EventDispatcher.ts
src/engine/EventEmitter.ts
src/engine/Graphics/Animation.ts
src/engine/index.ts
src/spec/AnimationSpec.ts
src/spec/EventEmitterSpec.ts

This PR adds a few improvements to animations that have been discussed offline 
* Adds new `EventEmitter` type which is a better typed event implementation
* Updates the `.events` type to be the new `EventEmitter`
* Adds the `frameIndex` of the current frame to the animation event
* Adds a new static builder for constructing animations from SpriteSheets 
```typescript
const spriteSheet = SpriteSheet.fromImageSource({...});
const anim = Animation.fromSpriteSheetCoordinates({
spriteSheet,
frameCoordinates: [
{x: 0, y: 5, duration: 100},
{x: 1, y: 5, duration: 200},
{x: 2, y: 5, duration: 100},
{x: 3, y: 5, duration: 500}
],
strategy: AnimationStrategy.PingPong
});
```

feat: Animation improvements fromSpriteSheetCoordinates + EventEmitter

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
src/engine/Graphics/PostProcessor/PostProcessor.ts
src/spec/PostProcessorSpec.ts

Closes #2416 
This PR adds some new default uniforms supplied to postprocessors automatically if they are present in the source
* `uniform float u_time_ms` - total playback time in milliseconds
* `uniform float u_elapsed_ms` - the elapsed time from the last frame in milliseconds
* `uniform vec2 u_resolution` - the resolution of the canvas (in pixels)
Custom uniforms can now be set in an optional `onUpdate()` function on postprocessors, the internal `shader.use()` is called for users.
Example using the CRT post processor, see gist https://gist.github.com/eonarheim/5ebb7f9161c10894935479e0caa0f6c7

feat: [#2416] Add Postprocessor hooks and default some uniforms

---

CHANGELOG.md
sandbox/index.html
sandbox/tests/screenelementpointer/index.html
sandbox/tests/screenelementpointer/index.ts
src/engine/ScreenElement.ts

Closes #2668
Update `ex.ScreenElement` to set a sensible default in it's constructor so it uses graphics bounds to capture pointers

fix: [#2668] ScreenElement pointer capture configured properly

---

CHANGELOG.md
sandbox/tests/ecs/index.html
sandbox/tests/ecs/index.ts
src/engine/EntityComponentSystem/Entity.ts
src/spec/EntitySpec.ts

Fixes #2685
Overriding existing components did not work because of deferred removal, this change forces an immediate removal when overriding.

fix: Overriding existing components

---

CHANGELOG.md
src/engine/Scene.ts
src/spec/SceneSpec.ts

Closes #2687 
- Adds a new method called `transfer()` to move entities from scene to scene, useful if you want an entity to only exist in 1 scene at a time

fix: [#2687] Add scene transfer method

---

CHANGELOG.md
src/engine/EntityComponentSystem/EntityManager.ts
src/spec/EntityManagerSpec.ts

Closes #2726
Properly clears internal state after entities have removed from the world

fix: [#2726] Entity manager memory leak

---

CHANGELOG.md
src/engine/TileMap/TileMap.ts

Closes #2732
Fixes bug where the current run of collider is not saved if the next tile has a custom collider

fix: [#2732] TileMap collider consolidation

---

src/engine/TileMap/TileMap.ts

This partially fixes #2763, by drawing all tiles if the tilemap uses the screen coordinate plane.

TileMap: Draw all tiles if screen coordinate plane is used

---

CHANGELOG.md
src/engine/Engine.ts
src/spec/InputMapperSpec.ts

Closes #2762
- Changes the input mapper execution order to run input mapping before clearing keyboard events per frame

fix: [#2762] wasPressed in input mapper

---

CHANGELOG.md
package.json
sandbox/tests/sound-loop/index.html
sandbox/tests/sound-loop/index.ts
src/engine/Interfaces/Audio.ts
src/engine/Resources/Sound/Sound.ts
src/engine/Resources/Sound/WebAudioInstance.ts
src/spec/SoundSpec.ts

This PR fixes a bug that caused looping Sound to be unstoppable when stopped then started in rapid succession. There were two issues, an errant await and not checking the result of an `indexOf` for -1

fix: bug where incorrect track was removed when stop/start in rapid succession

---

CHANGELOG.md
src/engine/Trigger.ts
src/spec/TriggerSpec.ts

Fixes issue where the incorrect type was being hinted in excalibur

fix: Trigger event signature type was incorrect

---

CHANGELOG.md
src/engine/Engine.ts

Add `ex.Engine.version` build string to engine

feat: Add  `ex.Engine.version` to report the current excalibur version build string

---

CHANGELOG.md
package.json
sandbox/src/game.ts
src/engine/Loader.ts
src/engine/Screen.ts
src/spec/ScreenSpec.ts

- Fixed issue where play button was hidden when going fullscreen mode
- Fixed issue where screen resizing caused artifacts on the loading screen
- Added new `ex.Screen.events`
- `screen.events.on('resize', (evt) => )` Will emit when the screen is resized
- `screen.events.on('fullscreen', (evt) => )` Will emit when the screen is changed into browser fullscreen mode
- `screen.events.on('pixelratio', (evt) => )` Will emit when the screen's pixel ratio changes (moving from a hidpi screen to a non, or vice versa)

fix/feat: Screen resizing artifacts + expose screen events!

---

CHANGELOG.md
src/engine/Graphics/FontCache.ts

This PR fixes a downward spiral that is possible on platforms with a slow couple frames. The `FontCache` font timeout to 500 ms and makes it configurable as a static `FontCache.FONT_TIMEOUT`. This is to help prevent a downward spiral on mobile devices that might take a long while to render a few starting frames causing the cache to repeatedly clear and never recover.

fix: Adjust font cache to prevent downward spiral on mobile

---

CHANGELOG.md
sandbox/tests/sprite-tint/index.ts
src/engine/Graphics/Graphic.ts
src/engine/Graphics/Raster.ts
src/engine/Util/Util.ts
src/spec/GraphicSpec.ts

Closes #2848 
- Fixes sprite tint constructor value passing
- Fixes sprite tint on cloned sprites
- Fixes width/height inconsistency discovered in new tests
- New tests

fix: #2848 Sprite tint respected in constructor

---

CHANGELOG.md
src/engine/Actions/ActionQueue.ts
src/engine/Actor.ts
src/engine/Events.ts
src/spec/ActionSpec.ts

Closes #2856
- Added `actionstart` and `actioncomplete` events to the Actor that are fired when an action starts and completes

feat: [#2856] Emit actionstart and actioncomplete events on actors

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Engine.ts
src/engine/Scene.ts
src/spec/SceneSpec.ts

This PR is the first a few adding more Scene specific APIs. In particular this adds a background color property to Scenes.

feat: Add Scene specific background color

---

CHANGELOG.md
src/engine/Camera.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/Colliders/CompositeCollider.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Graphics/TransformInterpolation.ts
src/spec/CameraSpec.ts

Fixes an issue spotted by @mattjennings where the camera is not interpolated during fixed update causing noticeable stutter on the screen with camera locked strategies

fix: Camera interpolation on fixed update

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Actor.ts
src/engine/Collision/ColliderComponent.ts
src/engine/Collision/CollisionSystem.ts
src/engine/Collision/Solver/ArcadeSolver.ts
src/engine/Collision/Solver/RealisticSolver.ts
src/engine/Events.ts

This PR adds new collision lifecycle convenience methods to `Actor`! This was possible before by wiring up an event handler. This is a super common pattern so now it's moved to Actor!
```typescript
class MyActor extends ex.Actor {
constructor(args: ex.ActorArgs) {
super(args);
}
onPreCollisionResolve(self: ex.Collider, other: ex.Collider, side: ex.Side, contact: ex.CollisionContact): void {
}
onPostCollisionResolve(self: ex.Collider, other: ex.Collider, side: ex.Side, contact: ex.CollisionContact): void {
}
onCollisionStart(self: ex.Collider, other: ex.Collider, side: ex.Side, contact: ex.CollisionContact): void {
}
onCollisionEnd(self: ex.Collider, other: ex.Collider): void {
}
}
```

feat: Collision lifecycle convenience methods on Actor

---

CHANGELOG.md
package-lock.json
src/engine/Graphics/Animation.ts
src/spec/AnimationSpec.ts
src/spec/MaterialRendererSpec.ts

This PR adds new property and methods overloads to `ex.Animation`
* `ex.Animation.currentFrameTimeLeft` will return the current time in milliseconds left in the current
* `ex.Animation.goToFrame(frameNumber: number, duration?: number)` now accepts an optional duration for the target frame

feat: Animation current time methods

---

CHANGELOG.md
package.json
src/engine/Collision/BodyComponent.ts
src/engine/Graphics/TransformInterpolation.ts
src/engine/Math/transform.ts
src/spec/GraphicsSystemSpec.ts
wallaby.js

This PR fixes an issue where parenting a entity with fixed updates on would cause a drawing flicker, transform interpolation now is aware of changing parents so it interpolates drawing continuously to prevent any flickering
https://github.com/excaliburjs/Excalibur/assets/612071/4605bd0d-7a05-4e74-a75a-98cf6a701fa6

fix: Fixed update interpolation on child entities

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Events.ts
src/engine/Graphics/GraphicsComponent.ts
src/engine/Graphics/GraphicsSystem.ts

This PR adds new graphics events and hooks that allow you to hook into graphics drawing before or after any drawing transformations have been applied
* `Actor.graphics.onPreTransformDraw` with the corresponding event `.on('pretransformdraw')`
* `Actor.graphics.onPostTransformDraw` with the corresponding event `.on('posttransformdraw')`
This is useful if you want to make changes to the transform or totally influence the draw transform DURING the draw step

feat: New graphics events

---

CHANGELOG.md
src/engine/Collision/Colliders/CompositeCollider.ts
src/spec/CompositeColliderSpec.ts

This PR fixes an issue where `CompositeColliders` nested inside each other would cause a crash at runtime because the narrowphase doesn't know how to collide with composites, only pieces.
The fix flattens composites so they can only ever be 1 level deep.

fix: Flatten composite colliders

---

src/engine/Engine.ts

…throw error if not
Closes #
- change 1
- change 2

fix: Add friendly error if canvasElementId missing

---

CHANGELOG.md
sandbox/src/game.ts
sandbox/tests/material/index.ts
sandbox/tests/sprite-tint/index.ts
site/docs/04-graphics/04.2-graphics-component.mdx
src/engine/Actor.ts
src/engine/Graphics/GraphicsComponent.ts
src/engine/Graphics/GraphicsGroup.ts
src/engine/Graphics/GraphicsSystem.ts
src/spec/ActorSpec.ts
src/spec/GraphicsComponentSpec.ts
src/spec/GraphicsGroupSpec.ts
src/spec/GraphicsSystemSpec.ts
src/spec/OffscreenSystemSpec.ts

This PR refactors the `GraphicsComponent` to be simpler.
1. Remove confusing Graphics Layering from `ex.GraphicsComponent`, recommend we use the `ex.GraphicsGroup` to manage this behavior
2. Update `ex.GraphicsGroup` to be consistent and use `offset` instead of `pos` for graphics relative positioning

refactor: Graphics Component simplification

---

CHANGELOG.md
src/engine/Collision/ColliderComponent.ts
src/engine/Collision/Colliders/CircleCollider.ts
src/engine/Collision/Colliders/ClosestLineJumpTable.ts
src/engine/Collision/Colliders/Collider.ts
src/engine/Collision/Colliders/CompositeCollider.ts
src/engine/Collision/Colliders/EdgeCollider.ts
src/engine/Collision/Colliders/PolygonCollider.ts
src/engine/Collision/Detection/DynamicTreeCollisionProcessor.ts
src/engine/Collision/Detection/RayCastHit.ts
src/engine/Collision/Index.ts
src/spec/CollisionShapeSpec.ts
src/spec/CompositeColliderSpec.ts

This PR adds `RayCastHit` returns as part of every raycast not just the physics world query!
* Additionally added the ray distance and the contact normal for the surface

feat: Raycast improvements with contact normal

---

CHANGELOG.md
src/engine/Graphics/Animation.ts
src/engine/Graphics/Graphic.ts
src/engine/Graphics/SpriteSheet.ts
src/spec/AnimationSpec.ts
src/spec/SpriteSheetSpec.ts

This PR implements new `ex.SpriteSheet.getSprite(..., options)`
You can now influence sprites directly out of the sprite sheet
```typescript
const sprite = ss.getSprite(0, 0, {
flipHorizontal: true,
flipVertical: true,
width: 200,
height: 201,
opacity: .5,
scale: ex.vec(2, 2),
origin: ex.vec(0, 1),
tint: ex.Color.Red,
rotation: 4
});
```
Also the animation helper  `ex.Animation.fromSpriteSheetCoordinates()` you can now pass any valid `ex.GraphicOptions` to influence the sprite per frame
```typescript
const anim = ex.Animation.fromSpriteSheetCoordinates({
spriteSheet: ss,
frameCoordinates: [
{x: 0, y: 0, duration: 100, options: { flipHorizontal: true }},
{x: 1, y: 0, duration: 100, options: { flipVertical: true }},
{x: 2, y: 0, …
```

feat: Implement SpriteSheet getSprite options

---

CHANGELOG.md
sandbox/tests/pointer/pointer.ts
src/engine/Camera.ts
src/engine/Debug/DebugSystem.ts
src/engine/Graphics/GraphicsComponent.ts
src/engine/Screen.ts
src/spec/ActorSpec.ts
src/spec/PointerInputSpec.ts

This PR fixes an issue discovered on the discord around pointer events and ScreenElements
- Fixed issue where pointer events did not work properly when using [[ScreenElement]]s
- Fixed issue where debug draw was not accurate when using *AndFill suffixed [[DisplayMode]]s

fix: Issue with pointer events on screen elements

---

CHANGELOG.md
src/engine/Label.ts
src/spec/LabelSpec.ts

Fixes an issue where an empty label constructor would crash `new ex.Label()` brought on the discord

fix: Empty label constructor

---

CHANGELOG.md
sandbox/tests/pointer/index.html
sandbox/tests/pointer/pointer.ts
src/engine/Util/Util.ts

This PR fixes an issue where CSS transforms confused the excalibur pointer system and caused clicks to land in the wrong spot

fix: Allow CSS transforms on canvas

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Graphics/Context/shader.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Particles.ts
src/spec/MaterialRendererSpec.ts

Closes #2896
- Fixed issue where Actor built in components could not be extended because of the way the Actor based type was built.
- Actors now use instance properties for built-ins instead of getters
- With the ECS refactor you can now subtype built-in `Components` and `.get(Builtin)` will return the correct subtype.
```typescript
class MyBodyComponent extends ex.BodyComponent {}
class MyActor extends ex.Actor {
constructor() {
super({})
this.removeComponent(ex.BodyComponent);
this.addComponent(new MyBodyComponent())
}
}
const myActor = new MyActor();
const myBody = myActor.get(ex.BodyComponent); // Returns the new MyBodyComponent subtype!
```

fix: [#2896] Allow component subtypes to work on extend Actors

---

CHANGELOG.md
src/engine/Graphics/Font.ts
src/spec/TextSpec.ts

Closes #2799
This PR changes the default base align on Fonts to Top, this is more in line with user expectations. 
This does change the default rendering to the top left instead of the bottom left.

fix: [#2799] Change default Font Base Align to Top

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Actor.ts
src/engine/Collision/ColliderComponent.ts
src/engine/Collision/Colliders/Collider.ts
src/engine/Collision/Colliders/CompositeCollider.ts
src/engine/Collision/Colliders/PolygonCollider.ts
src/engine/Collision/CollisionSystem.ts
src/engine/Collision/Detection/CollisionContact.ts
src/engine/Collision/PhysicsConfig.ts
src/engine/Events.ts
src/spec/ColliderComponentSpec.ts
src/spec/CollisionSpec.ts
src/spec/CompositeColliderSpec.ts

One stealth feature 
* onCollisionEnd events now include the last side and contact which is useful for collision logic
This PR fixes 2 issues:
1. Fixes an issue where a collider that was part of a contact that was deleted did not fire a collision end event, this was unexpected
2. Fixes an issue where you may want to have composite colliders behave as constituent colliders for the purposes of start/end collision events. A new property is added to physics config, the current behavior is the default which is `'together'`, this means the whole composite collider is treated as 1 collider for onCollisionStart/onCollisionEnd. Now you can configure a `separate` which will fire onCollisionStart/onCollisionEnd for every separate collider …

fix: Fire collisionend when collider deleted + Composite collision start/end strategy

---

CHANGELOG.md
sandbox/src/game.ts
sandbox/tests/router/index.ts
site/docs/02-fundamentals/05-transitions.mdx
site/docs/02-fundamentals/06-loaders.mdx
src/engine/Director/Director.ts
src/engine/Director/Transition.ts
src/engine/Engine.ts
src/engine/EntityComponentSystem/Entity.ts
src/engine/Scene.ts
src/engine/Util/Clock.ts
src/engine/Util/Coroutine.ts
src/engine/index.ts
src/spec/CoroutineSpec.ts
src/spec/DirectorSpec.ts
src/spec/EngineSpec.ts
src/spec/FadeInOutSpec.ts
src/spec/SceneSpec.ts
src/spec/TransistionSpec.ts
src/spec/util/TestUtils.ts

This PR fixes some Scene transition bugs
* If the root scene was overridden it would confuse the initial transition
* goto and goToScene now behave the same with regards to scene transitions
* Adds friendly warning instead of error when invalid scene update/draw's occur
* Switches Transitions to work via coroutine removing some update code in director

fix: Scene transition bugs + Coroutines

---

CHANGELOG.md
src/engine/EntityComponentSystem/Components/TransformComponent.ts
src/spec/TransformComponentSpec.ts

Closes #2933
This PR forces children to inherit their parent's coordinate plane, it will always be the coordinate plane of the top most parent.

fix: [#2933] Children inherit their coordinate plane

---

CHANGELOG.md
src/engine/Graphics/Context/material.ts
src/engine/Graphics/Context/vertex-layout.ts
src/engine/Graphics/Context/webgl-util.ts
src/spec/VertexLayoutSpec.ts

This PR fixes an issue where Firefox on Linux would throw an error when using custom Materials due to unused attributes caused by glsl compiler optimization.
Before it would throw and crash excalibur
Now after, it will log a warning because this is potentially a bug, or at minimum something you should look at

fix: Firefox + Linux custom shader issue with glsl compiler attribute optimization

---

CHANGELOG.md
src/engine/Director/Loader.ts
src/engine/Screen.ts
src/spec/ScreenSpec.ts
src/spec/util/TestUtils.ts

Fixed issue where unbounded containers would grow infinitely when using the following display modes:
* `DisplayMode.FillContainer`
* `DisplayMode.FitContainer`
* `DisplayMode.FitContainerAndFill`
* `DisplayMode.FitContainerAndZoom`
This works by using CSS percent to fill the container instead of calculating the size which would cause n+1 resizing when setting the size. Viewport screen dimensions will now support percent based sizes

fix: fit content resizing incorrectly

---

CHANGELOG.md
src/engine/Engine.ts
src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
src/engine/Screen.ts
src/spec/ScreenSpec.ts

This PR addresses some issues with webgl contexts
- Fixed issue when WebGL context lost occurs where there was no friendly output to the user
- Fixed issue where HiDPI scaling could accidentally scale past the 4k mobile limit, if the context would scale too large it will now attempt to recover by backing off.
- Added way to add custom WebGL context lost/recovered handlers for your game
```typescript
const game = new ex.Engine({
handleContextLost: (e) => {...},
handleContextRestored: (e) => {...}
})
```
Default context lost screen

fix: Handle webgl context lost + Recover from hidpi scale too large

---

src/engine/Engine.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext.ts
src/engine/Graphics/Context/ExcaliburGraphicsContext2DCanvas.ts
src/engine/Graphics/Context/ExcaliburGraphicsContextWebGL.ts
src/engine/Screen.ts

Fix issue caused by recent change to FitContainer where percent units were not accounted for when transforming coordinates

fix: Screen to world coord conversion when using fit container

---

CHANGELOG.md
src/engine/Context.ts
src/engine/Engine.ts
src/engine/Util/Clock.ts
src/engine/Util/Coroutine.ts
src/spec/ContextSpec.ts
src/spec/CoroutineSpec.ts
src/spec/FadeInOutSpec.ts

This PR adds an optional `ex.coroutine` timing parameter as an option bag to schedule when they are updated
```typescript
const result = ex.coroutine(engine, function * () {...}, { timing: 'postupdate' })
```
This PR also adds a way to set the `this` parameter for a generator
```typescript
const result = ex.coroutine({myThis: 'value'}, engine, function * () {...})
```
Additionally this PR removes the requirement to pass engine if done so under an Excalibur lifecycle
```typescript
const result = ex.coroutine(function * () {...});
```

feat: Allow coroutine lifecycles + support thisArg + remove engine requirement

---

CHANGELOG.md
src/engine/Resources/Font.ts
src/spec/FontSourceSpec.ts

- [ x :page_facing_up: changelog entry added (or not needed)
Closes #
- Fixed incomplete types for font options in `ex.FontSource().toFont(options)`

fix: incomplete types for options in ex.FontSource.toFont()

---

site/docs/04-graphics/04.1-text.mdx

Remove duplicate example of SpriteFont
Closes #
- Updated docs section  Graphics -> Text -> SpriteFont

fix: Update docs, SpriteFont 

---

CHANGELOG.md
src/engine/Color.ts
src/spec/ColorSpec.ts

=== :clipboard: PR Checklist :clipboard: ===
Closes #2983
- fix `Color.toHex()` and `Color._componentToHex()` to handle fractional numbers, negative numbers and colors with transparency
- add tests for `Color.toHex()`

fix: wrong hex color values

---

src/spec/_boot.ts

Some tests were failing when running on my macbook because the resolution of images from `toEqualImage()` were 2x what they should be. Simple fix was to set the devicePixelRatio of the browser to 1 at the start of the tests.

chore: ensure consistent toEqualImage() resolution when running on hidpi displays

---

src/engine/EntityComponentSystem/Entity.ts

Had a conversation here https://discord.com/channels/1195771303215513671/1232877562804305920
```
From example in https://excaliburjs.com/docs/entities:
const entityWithName = new ex.Entity({name: 'Named Entity'});
No overload matches this call.
Overload 1 of 2, '(options: EntityOptions<any>): Entity<any>', gave the following error.
Argument of type '{ name: string; }' is not assignable to parameter of type 'EntityOptions<any>'.
Property 'components' is missing in type '{ name: string; }' but required in type 'EntityOptions<any>'.
Overload 2 of 2, '(components?: any[] | undefined, name?: string | undefined): Entity<any>', gave the following error.
Object literal may only specify known properties, and 'name' does not exist in type 'any[]'.ts(2769)
Entity.d.ts(58, 5): 'components' is …
```

Make Entity Constructor's `components` option optional

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/MotionSystem.ts
src/spec/ActorSpec.ts

Closes #2922
- `actor.oldGlobalPos` returns the globalPosition from the previous frame
- `actor.getGlobalPos()` - use `actor.globalPos` instead
- `actor.getGlobalRotation()` - use `actor.globalRotation` instead
- `actor.getGlobalScale()` - use `actor.globalScale` instead
This required some changes to `MotionSystem` so that `globalPos` could be properly captured. Previously, the parent's transform may have already been updated in the system's update when processing a child entity, leading to an incorrect `oldGlobalPos` value. Now, the MotionSystem update captures the entity & all of its children at the same time, skipping any entities that have parents as to not capture them twice over.
This also deprecates other …

Add actor.oldGlobalPos, deprecate getGlobalPos in favour of globalPos getter

---

CHANGELOG.md
sandbox/tests/sprite/sprite.ts
site/docs/05-entity-component-system/05.1-entities.mdx
site/docs/05-entity-component-system/05.3-systems.mdx
site/docs/11-input/10.1-input.mdx
site/docusaurus.config.ts
site/src/pages/showcase/_data.ts
src/engine/Actor.ts
src/engine/Collision/BodyComponent.ts
src/engine/Collision/MotionSystem.ts
src/engine/Director/Director.ts
src/engine/EntityComponentSystem/Entity.ts
src/spec/ActorSpec.ts
src/spec/DirectorSpec.ts

Closes #3022
- Fixed `getSceneName` to use `scene`.
I didn't know how to use `_sceneToInstance` cache, so I replaced it with something simpler.

fix: getSceneName use scenes  #3022

---

CHANGELOG.md
karma.conf.js
package.json
src/engine/EntityComponentSystem/Entity.ts
src/engine/env.d.ts
src/engine/globals.d.ts
src/engine/tsconfig.json
webpack.config.js

This adds a "development" build of Excalibur that [bundlers can use](https://webpack.js.org/guides/package-exports/#providing-devtools-or-production-optimizations). It allows us to include code that can be used to help the user during development but still keep it out of production builds as to not affect performance / size. 
This requires removing the `module` field in package.json in favour of `exports`, which is OK (`exports` essentially supersedes `module`). **There is potential for breaking change** here, as any nested imports e.g. `'excalibur/dist/abc'` would now need to be added to this exports map. But I don't believe there was ever a reason to do that, since everything is exported from the excalibur.js file. (Types are …

Feat: provide development build for bundlers, warn on unadded entity

---

CHANGELOG.md
src/engine/Collision/Colliders/PolygonCollider.ts
src/spec/CollisionShapeSpec.ts

Fixes an issue brought in the discord where negative transforms would cause polygon winding to change causing collision logic to no longer function properly
https://github.com/excaliburjs/Excalibur/assets/612071/6f16b2a4-ac67-409a-9857-b2c51d70acbd

fix: Polygon winding correct after negative transforms

---

CHANGELOG.md
src/engine/Actor.ts
src/engine/EntityComponentSystem/Components/TransformComponent.ts
src/engine/Graphics/GraphicsSystem.ts
src/engine/Math/transform.ts
src/spec/GraphicsSystemSpec.ts
src/spec/TransformComponentSpec.ts

- Z-indexes are now relative to the parent's Z-index. You can get the global Z-index with the `globalZ` property on the Actor or TransformComponent.

Feat: z-indexes are relative to their parent

---

src/engine/Graphics/Canvas.ts

The combined type for the constructor property has no required fields. This way you don't have to add an empty object to the superclass's constructor when, for example, creating a Canvas subclass

feat: Added default value to Canvas constructor

---

src/engine/Math/Random.ts

Setting `null` on a variable of type `T` isn't valid in the eyes of TS

feat: removed invalid null as value from Random.shuffle()

---

site/docusaurus.config.ts

Tweaking the docusaurus configuration file, adding
```ts
blog: {
showReadingTime: true,
// Please change this to your repo.
// Remove this to remove the "edit this page" links.
editUrl: 'https://github.com/excaliburjs/Excalibur/tree/main/site/blog/',
rehypePlugins: [[rehypeRaw, rehypeRawOptions]],
postsPerPage: 'ALL',     //-----------------------------------------new
blogSidebarTitle: 'All posts',//-----------------------------------------new
blogSidebarCount: 'ALL',//-----------------------------------------new
},
```

doc config tweak

---

site/blog/2024-6-16-cellular-automata/cellularautonoma.mdx

- fixed typo of 'cognitive' in conclusion
- fixed typo of 'iteration' 
- made the word tilemap more consistent in capitalization

blogpost: Cellular Automata Typos

---

src/engine/TileMap/TileMap.ts

I thought EX had checks in the pipeline to prevent these types of TS inconsistencies.

fix: getTile return type should include null

---

src/engine/index.ts

I originally only intended to add `ActorEvents` to the exports, so it's possible to extend it without a dirty import:
`import {ActorEvents} from "excalibur/build/dist/Actor";`
But I don't see any reason to not export all of the Actor exports, because `isActor` could also be really useful for people extending core EX functionality.

feat: expose all actor exports

---

CHANGELOG.md
src/engine/Collision/Detection/CollisionContact.ts
src/spec/CollisionContactSpec.ts

Follow up from https://github.com/excaliburjs/Excalibur/issues/3121
- CollisionContact can be biased toward a collider by using `contact.bias(collider)`. This adjusts the contact so that the given collider is colliderA, and is helpful if you 
are doing mtv adjustments during precollision.

feat: add CollisionContact.bias(collider)

---

src/engine/EntityComponentSystem/System.ts

Closes #3123
- fix jsdoc for system class.

Update JSDoc for System class

---

src/engine/Collision/Colliders/ClosestLineJumpTable.ts
src/spec/CollisionShapeSpec.ts

Improves accuracy of PolygonPolygonClosestLine and ClosestLine functions. Big disclaimer, I heavily relied on ChatGPT for the math logic here... extra eyes greatly appreciated. I myself plan to do a deeper review on the math here before merging.
Before:
https://github.com/user-attachments/assets/a0d9d5d5-76e9-4e05-8459-15b6a48b0dcb
After:
https://github.com/user-attachments/assets/85d4410b-2bf2-4f51-90e2-4ee828a9693b
I also think there's a faster way to do the `PolygonPolygonClosestLine` logic. Right now it iterates over each side of the polygon, draws a line, and returns the shortest result. Potentially it could use SAT to determine the closest sides, but I had unexpected results
```ts
PolygonPolygonClosestLine(polygonA: …
```

fix: rewrite ClosestLine and PolygonPolygonClosestLine logic for improved accuracy on sloped polygons

---

CHANGELOG.md
sandbox/tests/loader-lockup/index.html
sandbox/tests/loader-lockup/index.ts
src/engine/Director/DefaultLoader.ts
src/spec/DefaultLoaderSpec.ts

Closes #3128
* Special case when no resources, consider it "loaded"

fix: [#3128] Unused scene loader locks up engine

---

src/engine/EntityComponentSystem/Entity.ts
src/engine/Particles/ParticleEmitter.ts
src/engine/Particles/Particles.ts

Closes #
- change 1
- change 2

fix: Emitter pool was created whether you used it or not

---

sandbox/tests/high-gravity-arcade/index.html
sandbox/tests/high-gravity-arcade/index.ts
src/engine/Collision/Colliders/CollisionJumpTable.ts
src/engine/Collision/CollisionSystem.ts
src/engine/Collision/Index.ts
src/engine/Collision/MotionSystem.ts
src/engine/Collision/PhysicsConfig.ts
src/engine/Collision/Solver/ArcadeSolver.ts
src/spec/CollisionContactSpec.ts

Related to #3135 
- Adds collision sub-stepping to discretize each frame further to help with fast moving objects
- Improves integration accuracy

feat: Implement Collision Sub-Stepping

---

CHANGELOG.md
src/engine/Context.ts
src/engine/Util/Coroutine.ts
src/spec/CoroutineSpec.ts

This PR gives users greater flexibility with Excalibur Coroutines!
* Optionally ask coroutines not to start immediately
```typescript
ex.coroutine(function* () { .. }, { autostart: false });
```
* New `CoroutineInstance` is returned that is also awaitable
```typescript
export interface CoroutineOptions {
timing?: ScheduledCallbackTiming;
autostart?: boolean;
}
export interface CoroutineInstance extends PromiseLike<void> {
isRunning(): boolean;
isComplete(): boolean;
done: Promise<void>;
generator: Generator<CoroutineInstance | number | Promise<any> | undefined, void, number>;
start: () => CoroutineInstance;
cancel: () => void;
then: Thenable;
[Symbol.iterator]: () => Generator<CoroutineInstance | number | Promise<any> | …
```

feat: Coroutine instances

---

.gitignore

Jetbrains IDEs create a `.idea` dir in each repository to store configurations (like `.vs` and `.vscode`).
I'm aware that `.git/info/exclude` can be used as a localized .gitignore file or `~/..config/git/ignore` for global ignores, so I'll leave it up to the maintainers if this solution is ok.
- Added `.idea` to `.gitignore` to prevent this dir from accidentally being committed.

feat: add Jetbrains .idea dir to .gitignore

---

CHANGELOG.md
src/engine/Math/vector.ts

Closes #3171
- `Vector.normalize()` return zero-vector (`(0,0)`) instead of `(0,1)` when normalizing a vector with a magnitude of 0

Feat: [#3171] normalize zero vector

---

CHANGELOG.md
sandbox/tests/trigger/trigger.ts
src/engine/Events.ts
src/engine/Trigger.ts

Couldn't get the [suggested setup](https://github.com/excaliburjs/Excalibur/issues/3157#issuecomment-2266842536) to work without adding a lot of extra (code) complexity. I'd recommend dropping that requirement, because it's a lot easier to implement by the developers themselves by adding the check in their own `filter` callback to assure an entity is of a specific type (and use `as ....` to placate TS if needed).
I'll finish the last 2 points on the checklist after there's a green light on my current implementation.
Closes #3157
- The action callback of Trigger now returns the entity that triggered it.
- General cleanup of Trigger class
- `target` is now 100% separate from `filter`, because that's what the functionality …

Feat: [#3157] return target on trigger

---

site/docs/02-fundamentals/02-conventions.mdx

Closes #3213
- add preceding `/` to Resources link

[#3213] Fix link typo in 02-conventions.mdx

---

CHANGELOG.md
src/engine/Graphics/Context/image-renderer/image-renderer.ts
src/engine/Graphics/Context/webgl-util.ts

Closes #3215
- Tests shader complexity starting with max texture slots

fix: [#3215] Check shader complexity to avoid crash on certain hardware

---

site/docs/02-fundamentals/04-events.mdx

https://kamranayub-docs-events-pubsu.excaliburjs.pages.dev/docs/events#pubsub-or-signal-based-event-bus
- Add a Shiki Twoslash example implementing custom event handling
- Show how to achieve a pub/sub emitter
- Show how to achieve higher strictness on event name handling
- Clean up existing verbiage and add some more context
- Inspired by @jyoung4242's [post](https://dev.to/excaliburjs/alien-waves-148m) about Signals and Pub/Sub, I noticed our docs lacked info about this use case. When I dug into it, the existing example was not enough to help me create a custom event so I had to look at the engine source.

docs(events): Fuller example with pub/sub

---

site/docs/02-fundamentals/02-conventions.mdx
site/docs/07-actions/06.1-actions.mdx

Closes #3236
- The line `this.repeatForever(ctx => {` is now `this.actions.repeatForever(ctx => {`.

[#3236] Fix missing word typo in 06.1-actions.mdx

---

CHANGELOG.md
karma.conf.js
sandbox/images/arrows.svg
sandbox/src/game.ts
src/engine/Graphics/ImageSource.ts
src/engine/Graphics/Sprite.ts
src/spec/ImageSourceSpec.ts
src/spec/images/GraphicsImageSourceSpec/arrows.svg
wallaby.js

Closes #150 
- Implement svg source string support 
- Allow optional sprite arguments `.toSprite(options:? SpriteOptions)`

feat: [#150] Implement SVG support in ImageSource with static builder

---

CHANGELOG.md
src/engine/Input/Keyboard.ts
src/engine/Input/PointerEventReceiver.ts

fix: [#3087] `blockInput: true` blocks input accessors

---

site/docs/02-fundamentals/02-conventions.mdx
site/docs/07-actions/06.1-actions.mdx
site/docs/13-plugins/15-tiled-plugin.mdx

Closes #
- Fix a typo in documentation: `You an mark a layer solid by setting...` to `You can mark a layer solid by setting...`

Fix Typo in Documentation: 15-tiled-plugin

---

CHANGELOG.md
src/engine/Input/PointerEventReceiver.ts
src/spec/PointerInputSpec.ts

fix: [#3250] Stop cancelled pointer events from bubbling to the top level

---

.vscode/settings.json
CHANGELOG.md
sandbox/tests/bezier/index.html
sandbox/tests/bezier/index.ts
src/engine/Actions/Action/CurveBy.ts
src/engine/Actions/Action/CurveTo.ts
src/engine/Actions/ActionContext.ts
src/engine/Actions/ActionsComponent.ts
src/engine/Actions/Index.ts
src/engine/Math/bezier-curve.ts
src/engine/Math/index.ts
src/spec/BezierSpec.ts
src/spec/CurveActionSpec.ts

https://github.com/user-attachments/assets/e2bdff59-7551-4652-a4ba-7ce78d7eeaf8
This PR implements new CurveTo/CurveBy action for moving actors in a Bezier curve
```typescript
const curve = new ex.BezierCurve({
controlPoints: [ex.vec(0, 700), ex.vec(100, -300), ex.vec(150, 800), ex.vec(500, 100)],
quality: 10
});
actor.actions.repeatForever((ctx) => {
ctx.curveTo({
controlPoints: [ex.vec(100, -300), ex.vec(150, 800), ex.vec(500, 100)],
durationMs: 6000
});
ctx.curveBy({
controlPoints: [ex.vec(100, 0), ex.vec(-100, 0), ex.vec(0, 300)],
durationMs: 1000
});
ctx.curveTo({
controlPoints: [ex.vec(150, 800), ex.vec(100, -300), ex.vec(0, 700)],
durationMs: 6000
});
});
```

feat: Add ex.BezierCurve and CurveBy/CurveTo actions

---

CHANGELOG.md
src/engine/Graphics/GraphicsGroup.ts

Closes #3284 
- reuse single cumulative bounding box for local bounds calculation of `GraphicsGroup` to reduce per-draw allocations

[#3284] perf: reduce allocations for GraphicsGroup draw calls

---

site/docs/05-user-interface/02-screen-elements.mdx

Hi
I was browsing the documentation the other day and noticed a link on https://excaliburjs.com/docs/screen-elements that I think is broken. Though I should help by fixing it.
The contribution guide said to open an issue before a PR, but I also found [this discussion post](https://github.com/excaliburjs/Excalibur/discussions/3003) about proposing updates to the documentation. I hope this is fine :)

fixes broken link on screen element page.

---

CHANGELOG.md
src/engine/Collision/Colliders/CollisionJumpTable.ts

Fixes issue where the realistic solver gets confused with TileMaps mentioned in the discord https://discord.com/channels/1195771303215513671/1320140196372676692
The issue causes massive overcorrection because it _appears_ to the solver that the collider in a composite is further away from the contact than it actually is.
https://github.com/user-attachments/assets/45bceff6-ab06-40b7-9c91-a4886505c124
In the fix we shift the collider local side by the offset (which is what is used in composites to position relative to the transform). This gives an accurate pos for the contact point
https://github.com/user-attachments/assets/db83f756-8aa0-43a0-99da-72a7bebbb772

fix: CompositeCollider behavior affecting TileMap w/Realistic Solver

---

CHANGELOG.md
sandbox/tests/input/gamepad.ts
src/engine/Input/Gamepad.ts

Closes #3317
Tested on a Nintendo Switch Pro controller
https://github.com/user-attachments/assets/e331d58f-defc-42ab-9d7b-1cd8a0e91ef5
- Enumerates all buttons not just the ones in the enum
- Update visual integration test

fix: [#3317] gamepad support non standard buttons

---

src/engine/Actor.ts
src/spec/ActorSpec.ts

Actor.ts: updated .clone() method to test for non-null collider prior to attempting to clone.
Added test 'can be cloned with null collider; to ActorSpec.ts
This fixes issue reported in discord on 1/23/25:
https://discord.com/channels/1195771303215513671/1195779955611672598/1332073907213308055
Issue:

BUG: fixed actor cloning of null collider, added test 

---

src/engine/Collision/Colliders/Shape.ts
src/engine/Collision/CollisionSystem.ts
src/engine/Collision/Detection/CollisionContact.ts
src/engine/Collision/Solver/ArcadeSolver.ts

This PR fixes and issue where composite colliders in the "together" strategy contacts were being resolved multiple times in the ArcadeSolver causing visual jitter/artifacts

fix: composite multi contact

---

CHANGELOG.md
sandbox/src/game.ts
src/engine/Actor.ts
src/engine/Director/Director.ts
src/engine/Engine.ts
src/engine/Scene.ts

* Fixed `onTransition` on the initial scene transition
* Pipes events navigation events up to engine
* Adds transitionstart/end to scenes
* Adds missing `as const`s

fix: Add missing events for transitions + Fix onTransition for initial scene transition

---

site/docs/00-tutorial/03-step-bird-and-ground.mdx

I found this small typo in the docs while reading it, thanks for the good work on the engine, the docs are very good compared to other engines :)

docs: fix typo "n Excalibur" -> "in Excalibur" in tutorial step 03

---

site/docs/09-math/07-random.mdx
src/engine/Math/Random.ts
src/spec/vitest/RandomSpec.ts

3 files changed
- Random.ts
- 07-random.mdx
- RandomSpec.ts
added static intialSeed form Date.now() and an incrementing offset.
also, this ensures that the actual seed used is available property
moved public seed  to private _seed
added getter for seed
in constructor(), if no seed provided it pulls from the 'next' seed in the incrementing list
updated documentation to reflect new functionality
-added 2 tests
- will have a seed even if not passed into constructor
- can have sequential random instances with unique seeds
- added tests
- all tests pass locally
- created test project to exercise new logic with favorable results
- updated docs

fix: ex.Random improve unique seeding on constructor w/o provided seed

---

CHANGELOG.md
src/engine/Graphics/Animation.ts
src/spec/vitest/AnimationSpec.ts

Feature requested on the discord: https://discord.com/channels/1195771303215513671/1400805035503390721
arbitrary meta data can now be added for an `Animation`
```ts
const rect = new ex.Rectangle({
width: 100,
height: 100,
color: ex.Color.Blue
});
const anim = new ex.Animation({
frames: [
{
graphic: rect,
duration: 100
}
],
data: { someKey: 'someValue' }
});
console.log(anim.data.get('someKey')) // someValue
anim.data.set('otherKey', 'otherValue')
console.log(anim.data.get('otherKey')) // otherValue
```
`fromSpriteSheet(...)` now also accepts data as an optional argument.
```ts
const anim = ex.Animation.fromSpriteSheet(someSpriteSheet, [0, 1, 2, 3], 100, ex.AnimationStrategy.Freeze, {
someKey: 'someValue'
});
```
as well as …

feat: Support meta data for Animation

---

CHANGELOG.md
src/engine/Particles/ParticleEmitter.ts
src/engine/Particles/Particles.ts
src/spec/vitest/ParticleSpec.ts

=== :clipboard: PR Checklist :clipboard: ===
Closes #3503
Bug raised in Discord:
https://discord.com/channels/1195771303215513671/1408751467808034936
- The ParticleEmitter passes its z value down to particles when configured for Global space

fix: Apply z index to particles [#3503]
